

 - name: Set input params for az_advisor_configuration_get
   set_fact: 
     az_advisor_configuration_get:
       input: 
         ###  Optional parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
 - debug: msg="{{ az_advisor_configuration_get }}"          
 - name: "az advisor configuration get: Get Azure Advisor configuration." 
   command: |                                      
     az advisor configuration get                            
                 {%if az_advisor_configuration_get.input['resource-group'] %} --resource-group az_advisor_configuration_get.input['resource-group'] {%endif %} 
   register: output  
 - set_fact: 
    az_advisor_configuration_get: "{{ az_advisor_configuration_get|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_advisor_configuration_get }}" 
