

 - name: Set input params for az_batch_application_summary_list
   set_fact: 
     az_batch_application_summary_list:
       input: 
         ###  Optional parameter. Batch service endpoint. Alternatively, set by environment variable: AZURE_BATCH_ENDPOINT.  ### 
        'account-endpoint': "{{ item['account-endpoint'] | default('') }}" 
         ###  Optional parameter. Batch account key. Alternatively, set by environment variable: AZURE_BATCH_ACCESS_KEY.  ### 
        'account-key': "{{ item['account-key'] | default('') }}" 
         ###  Optional parameter. Batch account name. Alternatively, set by environment variable: AZURE_BATCH_ACCOUNT.  ### 
        'account-name': "{{ item['account-name'] | default('') }}" 
 - debug: msg="{{ az_batch_application_summary_list }}"          
 - name: "az batch application summary list: Lists all of the applications available in the specified account." 
   command: |                                      
     az batch application summary list                            
                 {%if az_batch_application_summary_list.input['account-endpoint'] %} --account-endpoint az_batch_application_summary_list.input['account-endpoint'] {%endif %} 
                 {%if az_batch_application_summary_list.input['account-key'] %} --account-key az_batch_application_summary_list.input['account-key'] {%endif %} 
                 {%if az_batch_application_summary_list.input['account-name'] %} --account-name az_batch_application_summary_list.input['account-name'] {%endif %} 
   register: output  
 - set_fact: 
    az_batch_application_summary_list: "{{ az_batch_application_summary_list|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_batch_application_summary_list }}" 
