

 - name: Set input params for az_batch_application_show
   set_fact: 
     az_batch_application_show:
       input: 
         ###  Required parameter. The ID of the application.  ### 
        'application-id': "{{ item['application-id'] | default('') }}" 
         ###  Required parameter. Name of the Batch account.  ### 
        'name': "{{ item['name'] | default('') }}" 
         ###  Required parameter. Name of the resource group.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
 - debug: msg="{{ az_batch_application_show }}"          
 - name: "az batch application show: Gets information about the specified application." 
   command: |                                      
     az batch application show                            
                 --application-id {{ az_batch_application_show.input['application-id'] }} 
                 --name {{ az_batch_application_show.input['name'] }} 
                 --resource-group {{ az_batch_application_show.input['resource-group'] }} 
   register: output  
 - set_fact: 
    az_batch_application_show: "{{ az_batch_application_show|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_batch_application_show }}" 
