

 - name: Set input params for az_batch_application_package_show
   set_fact: 
     az_batch_application_package_show:
       input: 
         ###  Required parameter. The ID of the application.  ### 
        'application-id': "{{ item['application-id'] | default('') }}" 
         ###  Required parameter. Name of the Batch account.  ### 
        'name': "{{ item['name'] | default('') }}" 
         ###  Required parameter. Name of the resource group.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
         ###  Required parameter. The version of the application.  ### 
        'version': "{{ item['version'] | default('') }}" 
 - debug: msg="{{ az_batch_application_package_show }}"          
 - name: "az batch application package show: Gets information about the specified application package." 
   command: |                                      
     az batch application package show                            
                 --application-id {{ az_batch_application_package_show.input['application-id'] }} 
                 --name {{ az_batch_application_package_show.input['name'] }} 
                 --resource-group {{ az_batch_application_package_show.input['resource-group'] }} 
                 --version {{ az_batch_application_package_show.input['version'] }} 
   register: output  
 - set_fact: 
    az_batch_application_package_show: "{{ az_batch_application_package_show|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_batch_application_package_show }}" 
