

 - name: Set input params for az_batch_application_set
   set_fact: 
     az_batch_application_set:
       input: 
         ###  Required parameter. The ID of the application.  ### 
        'application-id': "{{ item['application-id'] | default('') }}" 
         ###  Required parameter. Name of the Batch account.  ### 
        'name': "{{ item['name'] | default('') }}" 
         ###  Required parameter. Name of the resource group.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
         ###  Optional parameter. Specify to indicate whether packages within the application may be overwritten using the same version string. Specify either 'true' or 'false' to update the property.  ### 
        'allow-updates': "{{ item['allow-updates'] | default('') }}" 
         ###  Optional parameter. The package to use if a client requests the application but does not specify a version.  ### 
        'default-version': "{{ item['default-version'] | default('') }}" 
         ###  Optional parameter. The display name for the application.  ### 
        'display-name': "{{ item['display-name'] | default('') }}" 
 - debug: msg="{{ az_batch_application_set }}"          
 - name: "az batch application set: Update properties for a Batch application." 
   command: |                                      
     az batch application set                            
                 --application-id {{ az_batch_application_set.input['application-id'] }} 
                 --name {{ az_batch_application_set.input['name'] }} 
                 --resource-group {{ az_batch_application_set.input['resource-group'] }} 
                 {%if az_batch_application_set.input['allow-updates'] %} --allow-updates az_batch_application_set.input['allow-updates'] {%endif %} 
                 {%if az_batch_application_set.input['default-version'] %} --default-version az_batch_application_set.input['default-version'] {%endif %} 
                 {%if az_batch_application_set.input['display-name'] %} --display-name az_batch_application_set.input['display-name'] {%endif %} 
   register: output  
 - set_fact: 
    az_batch_application_set: "{{ az_batch_application_set|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_batch_application_set }}" 
