

 - name: Set input params for az_batch_application_package_activate
   set_fact: 
     az_batch_application_package_activate:
       input: 
         ###  Required parameter. The ID of the application.  ### 
        'application-id': "{{ item['application-id'] | default('') }}" 
         ###  Required parameter. The format of the application package binary file.  ### 
        'format': "{{ item['format'] | default('') }}" 
         ###  Required parameter. Name of the Batch account.  ### 
        'name': "{{ item['name'] | default('') }}" 
         ###  Required parameter. Name of the resource group.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
         ###  Required parameter. The version of the application to activate.  ### 
        'version': "{{ item['version'] | default('') }}" 
 - debug: msg="{{ az_batch_application_package_activate }}"          
 - name: "az batch application package activate: Activates a Batch application package." 
   command: |                                      
     az batch application package activate                            
                 --application-id {{ az_batch_application_package_activate.input['application-id'] }} 
                 --format {{ az_batch_application_package_activate.input['format'] }} 
                 --name {{ az_batch_application_package_activate.input['name'] }} 
                 --resource-group {{ az_batch_application_package_activate.input['resource-group'] }} 
                 --version {{ az_batch_application_package_activate.input['version'] }} 
   register: output  
 - set_fact: 
    az_batch_application_package_activate: "{{ az_batch_application_package_activate|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_batch_application_package_activate }}" 
