

 - name: Set input params for az_functionapp_deployment_source_config_zip
   set_fact: 
     az_functionapp_deployment_source_config_zip:
       input: 
         ###  Required parameter. Name of the function app.  ### 
        'name': "{{ item['name'] | default('') }}" 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
         ###  Required parameter.   ### 
        'src': "{{ item['src'] | default('') }}" 
 - debug: msg="{{ az_functionapp_deployment_source_config_zip }}"          
 - name: "az functionapp deployment source config-zip: Perform deployment using the kudu zip push deployment for a function app." 
   command: |                                      
     az functionapp deployment source config-zip                            
                 --name {{ az_functionapp_deployment_source_config_zip.input['name'] }} 
                 --resource-group {{ az_functionapp_deployment_source_config_zip.input['resource-group'] }} 
                 --src {{ az_functionapp_deployment_source_config_zip.input['src'] }} 
   register: output  
 - set_fact: 
    az_functionapp_deployment_source_config_zip: "{{ az_functionapp_deployment_source_config_zip|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_functionapp_deployment_source_config_zip }}" 
