

 - name: Set input params for az_functionapp_deployment_list_publishing_profiles
   set_fact: 
     az_functionapp_deployment_list_publishing_profiles:
       input: 
         ###  Required parameter. Name of the function app.  ### 
        'name': "{{ item['name'] | default('') }}" 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
 - debug: msg="{{ az_functionapp_deployment_list_publishing_profiles }}"          
 - name: "az functionapp deployment list-publishing-profiles: " 
   command: |                                      
     az functionapp deployment list-publishing-profiles                            
                 --name {{ az_functionapp_deployment_list_publishing_profiles.input['name'] }} 
                 --resource-group {{ az_functionapp_deployment_list_publishing_profiles.input['resource-group'] }} 
   register: output  
 - set_fact: 
    az_functionapp_deployment_list_publishing_profiles: "{{ az_functionapp_deployment_list_publishing_profiles|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_functionapp_deployment_list_publishing_profiles }}" 
