

 - name: Set input params for az_functionapp_config_ssl_list
   set_fact: 
     az_functionapp_config_ssl_list:
       input: 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
 - debug: msg="{{ az_functionapp_config_ssl_list }}"          
 - name: "az functionapp config ssl list: List SSL certificates for a function app." 
   command: |                                      
     az functionapp config ssl list                            
                 --resource-group {{ az_functionapp_config_ssl_list.input['resource-group'] }} 
   register: output  
 - set_fact: 
    az_functionapp_config_ssl_list: "{{ az_functionapp_config_ssl_list|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_functionapp_config_ssl_list }}" 
