

 - name: Set input params for az_functionapp_config_hostname_list
   set_fact: 
     az_functionapp_config_hostname_list:
       input: 
         ###  Required parameter. Name of the function app.  ### 
        'name': "{{ item['name'] | default('') }}" 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
 - debug: msg="{{ az_functionapp_config_hostname_list }}"          
 - name: "az functionapp config hostname list: List all hostname bindings for a function app." 
   command: |                                      
     az functionapp config hostname list                            
                 --name {{ az_functionapp_config_hostname_list.input['name'] }} 
                 --resource-group {{ az_functionapp_config_hostname_list.input['resource-group'] }} 
   register: output  
 - set_fact: 
    az_functionapp_config_hostname_list: "{{ az_functionapp_config_hostname_list|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_functionapp_config_hostname_list }}" 
