

 - name: Set input params for az_functionapp_config_appsettings_delete
   set_fact: 
     az_functionapp_config_appsettings_delete:
       input: 
         ###  Required parameter. Name of the function app.  ### 
        'name': "{{ item['name'] | default('') }}" 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
         ###  Required parameter. Space separated app setting names.  ### 
        'setting-names': "{{ item['setting-names'] | default('') }}" 
 - debug: msg="{{ az_functionapp_config_appsettings_delete }}"          
 - name: "az functionapp config appsettings delete: " 
   command: |                                      
     az functionapp config appsettings delete                            
                 --name {{ az_functionapp_config_appsettings_delete.input['name'] }} 
                 --resource-group {{ az_functionapp_config_appsettings_delete.input['resource-group'] }} 
                 --setting-names {{ az_functionapp_config_appsettings_delete.input['setting-names'] }} 
   register: output  
 - set_fact: 
    az_functionapp_config_appsettings_delete: "{{ az_functionapp_config_appsettings_delete|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_functionapp_config_appsettings_delete }}" 
