

 - name: Set input params for az_functionapp_deployment_source_config_local_git
   set_fact: 
     az_functionapp_deployment_source_config_local_git:
       input: 
         ###  Required parameter. Name of the function app.  ### 
        'name': "{{ item['name'] | default('') }}" 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
 - debug: msg="{{ az_functionapp_deployment_source_config_local_git }}"          
 - name: "az functionapp deployment source config-local-git: Get a URL for a git repository endpoint to clone and push to for function app deployment." 
   command: |                                      
     az functionapp deployment source config-local-git                            
                 --name {{ az_functionapp_deployment_source_config_local_git.input['name'] }} 
                 --resource-group {{ az_functionapp_deployment_source_config_local_git.input['resource-group'] }} 
   register: output  
 - set_fact: 
    az_functionapp_deployment_source_config_local_git: "{{ az_functionapp_deployment_source_config_local_git|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_functionapp_deployment_source_config_local_git }}" 
