

 - name: Set input params for az_functionapp_config_ssl_delete
   set_fact: 
     az_functionapp_config_ssl_delete:
       input: 
         ###  Required parameter. The ssl cert thumbprint.  ### 
        'certificate-thumbprint': "{{ item['certificate-thumbprint'] | default('') }}" 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
 - debug: msg="{{ az_functionapp_config_ssl_delete }}"          
 - name: "az functionapp config ssl delete: Delete an SSL certificate from a function app." 
   command: |                                      
     az functionapp config ssl delete                            
                 --certificate-thumbprint {{ az_functionapp_config_ssl_delete.input['certificate-thumbprint'] }} 
                 --resource-group {{ az_functionapp_config_ssl_delete.input['resource-group'] }} 
   register: output  
 - set_fact: 
    az_functionapp_config_ssl_delete: "{{ az_functionapp_config_ssl_delete|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_functionapp_config_ssl_delete }}" 
