

 - name: Set input params for az_functionapp_config_ssl_unbind
   set_fact: 
     az_functionapp_config_ssl_unbind:
       input: 
         ###  Required parameter. The ssl cert thumbprint.  ### 
        'certificate-thumbprint': "{{ item['certificate-thumbprint'] | default('') }}" 
         ###  Required parameter. Name of the function app.  ### 
        'name': "{{ item['name'] | default('') }}" 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
 - debug: msg="{{ az_functionapp_config_ssl_unbind }}"          
 - name: "az functionapp config ssl unbind: Unbind an SSL certificate from a function app." 
   command: |                                      
     az functionapp config ssl unbind                            
                 --certificate-thumbprint {{ az_functionapp_config_ssl_unbind.input['certificate-thumbprint'] }} 
                 --name {{ az_functionapp_config_ssl_unbind.input['name'] }} 
                 --resource-group {{ az_functionapp_config_ssl_unbind.input['resource-group'] }} 
   register: output  
 - set_fact: 
    az_functionapp_config_ssl_unbind: "{{ az_functionapp_config_ssl_unbind|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_functionapp_config_ssl_unbind }}" 
