

 - name: Set input params for az_functionapp_deployment_source_delete
   set_fact: 
     az_functionapp_deployment_source_delete:
       input: 
         ###  Required parameter. Name of the function app.  ### 
        'name': "{{ item['name'] | default('') }}" 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
 - debug: msg="{{ az_functionapp_deployment_source_delete }}"          
 - name: "az functionapp deployment source delete: Delete a source control deployment configuration." 
   command: |                                      
     az functionapp deployment source delete                            
                 --name {{ az_functionapp_deployment_source_delete.input['name'] }} 
                 --resource-group {{ az_functionapp_deployment_source_delete.input['resource-group'] }} 
   register: output  
 - set_fact: 
    az_functionapp_deployment_source_delete: "{{ az_functionapp_deployment_source_delete|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_functionapp_deployment_source_delete }}" 
