

 - name: Set input params for az_functionapp_config_hostname_delete
   set_fact: 
     az_functionapp_config_hostname_delete:
       input: 
         ###  Required parameter. Hostname assigned to the site, such as custom domains.  ### 
        'hostname': "{{ item['hostname'] | default('') }}" 
         ###  Required parameter. Name of the function app.  ### 
        'name': "{{ item['name'] | default('') }}" 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
 - debug: msg="{{ az_functionapp_config_hostname_delete }}"          
 - name: "az functionapp config hostname delete: Unbind a hostname from a function app." 
   command: |                                      
     az functionapp config hostname delete                            
                 --hostname {{ az_functionapp_config_hostname_delete.input['hostname'] }} 
                 --name {{ az_functionapp_config_hostname_delete.input['name'] }} 
                 --resource-group {{ az_functionapp_config_hostname_delete.input['resource-group'] }} 
   register: output  
 - set_fact: 
    az_functionapp_config_hostname_delete: "{{ az_functionapp_config_hostname_delete|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_functionapp_config_hostname_delete }}" 
