

 - name: Set input params for az_group_deployment_show
   set_fact: 
     az_group_deployment_show:
       input: 
         ###  Required parameter. The deployment name.  ### 
        'name': "{{ item['name'] | default('') }}" 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
 - debug: msg="{{ az_group_deployment_show }}"          
 - name: "az group deployment show: Gets a deployment." 
   command: |                                      
     az group deployment show                            
                 --name {{ az_group_deployment_show.input['name'] }} 
                 --resource-group {{ az_group_deployment_show.input['resource-group'] }} 
   register: output  
 - set_fact: 
    az_group_deployment_show: "{{ az_group_deployment_show|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_group_deployment_show }}" 
