

 - name: Set input params for az_group_deployment_wait
   set_fact: 
     az_group_deployment_wait:
       input: 
         ###  Required parameter. The deployment name.  ### 
        'name': "{{ item['name'] | default('') }}" 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
         ###  Optional parameter. Wait until created with 'provisioningState' at 'Succeeded'.  ### 
        'created': "{{ item['created'] | default('') }}" 
         ###  Optional parameter. Wait until the condition satisfies a custom JMESPath query. E.g. provisioningState!='InProgress', instanceView.statuses[?code=='PowerState/running'].  ### 
        'custom': "{{ item['custom'] | default('') }}" 
         ###  Optional parameter. Wait until deleted.  ### 
        'deleted': "{{ item['deleted'] | default('') }}" 
         ###  Optional parameter. Wait until the resource exists.  ### 
        'exists': "{{ item['exists'] | default('') }}" 
         ###  Optional parameter. Polling interval in seconds.  ### 
        'interval': "{{ item['interval'] | default('') }}" 
         ###  Optional parameter. Maximum wait in seconds.  ### 
        'timeout': "{{ item['timeout'] | default('') }}" 
         ###  Optional parameter. Wait until updated with provisioningState at 'Succeeded'.  ### 
        'updated': "{{ item['updated'] | default('') }}" 
 - debug: msg="{{ az_group_deployment_wait }}"          
 - name: "az group deployment wait: Place the CLI in a waiting state until a deployment condition is met." 
   command: |                                      
     az group deployment wait                            
                 --name {{ az_group_deployment_wait.input['name'] }} 
                 --resource-group {{ az_group_deployment_wait.input['resource-group'] }} 
                 {%if az_group_deployment_wait.input['created'] %} --created az_group_deployment_wait.input['created'] {%endif %} 
                 {%if az_group_deployment_wait.input['custom'] %} --custom az_group_deployment_wait.input['custom'] {%endif %} 
                 {%if az_group_deployment_wait.input['deleted'] %} --deleted az_group_deployment_wait.input['deleted'] {%endif %} 
                 {%if az_group_deployment_wait.input['exists'] %} --exists az_group_deployment_wait.input['exists'] {%endif %} 
                 {%if az_group_deployment_wait.input['interval'] %} --interval az_group_deployment_wait.input['interval'] {%endif %} 
                 {%if az_group_deployment_wait.input['timeout'] %} --timeout az_group_deployment_wait.input['timeout'] {%endif %} 
                 {%if az_group_deployment_wait.input['updated'] %} --updated az_group_deployment_wait.input['updated'] {%endif %} 
   register: output  
 - set_fact: 
    az_group_deployment_wait: "{{ az_group_deployment_wait|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_group_deployment_wait }}" 
