

 - name: Set input params for az_group_deployment_operation_list
   set_fact: 
     az_group_deployment_operation_list:
       input: 
         ###  Required parameter. The deployment name.  ### 
        'name': "{{ item['name'] | default('') }}" 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
         ###  Optional parameter. The number of results to return.  ### 
        'top': "{{ item['top'] | default('') }}" 
 - debug: msg="{{ az_group_deployment_operation_list }}"          
 - name: "az group deployment operation list: Gets all deployments operations for a deployment." 
   command: |                                      
     az group deployment operation list                            
                 --name {{ az_group_deployment_operation_list.input['name'] }} 
                 --resource-group {{ az_group_deployment_operation_list.input['resource-group'] }} 
                 {%if az_group_deployment_operation_list.input['top'] %} --top az_group_deployment_operation_list.input['top'] {%endif %} 
   register: output  
 - set_fact: 
    az_group_deployment_operation_list: "{{ az_group_deployment_operation_list|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_group_deployment_operation_list }}" 
