

 - name: Set input params for az_group_deployment_export
   set_fact: 
     az_group_deployment_export:
       input: 
         ###  Required parameter. The deployment name.  ### 
        'name': "{{ item['name'] | default('') }}" 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
 - debug: msg="{{ az_group_deployment_export }}"          
 - name: "az group deployment export: Export the template used for a deployment." 
   command: |                                      
     az group deployment export                            
                 --name {{ az_group_deployment_export.input['name'] }} 
                 --resource-group {{ az_group_deployment_export.input['resource-group'] }} 
   register: output  
 - set_fact: 
    az_group_deployment_export: "{{ az_group_deployment_export|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_group_deployment_export }}" 
