

 - name: Set input params for az_group_deployment_delete
   set_fact: 
     az_group_deployment_delete:
       input: 
         ###  Required parameter. The deployment name.  ### 
        'name': "{{ item['name'] | default('') }}" 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
 - debug: msg="{{ az_group_deployment_delete }}"          
 - name: "az group deployment delete: Deletes a deployment from the deployment history." 
   command: |                                      
     az group deployment delete                            
                 --name {{ az_group_deployment_delete.input['name'] }} 
                 --resource-group {{ az_group_deployment_delete.input['resource-group'] }} 
   register: output  
 - set_fact: 
    az_group_deployment_delete: "{{ az_group_deployment_delete|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_group_deployment_delete }}" 
