

 - name: Set input params for az_group_deployment_validate
   set_fact: 
     az_group_deployment_validate:
       input: 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
         ###  Optional parameter. Incremental (only add resources to resource group) or Complete (remove extra resources from resource group).  ### 
        'mode': "{{ item['mode'] | default('') }}" 
         ###  Optional parameter. Supply deployment parameter values.  ### 
        'parameters': "{{ item['parameters'] | default('') }}" 
         ###  Optional parameter. A template file path in the file system.  ### 
        'template-file': "{{ item['template-file'] | default('') }}" 
         ###  Optional parameter. A uri to a remote template file.  ### 
        'template-uri': "{{ item['template-uri'] | default('') }}" 
 - debug: msg="{{ az_group_deployment_validate }}"          
 - name: "az group deployment validate: Validate whether a template is syntactically correct." 
   command: |                                      
     az group deployment validate                            
                 --resource-group {{ az_group_deployment_validate.input['resource-group'] }} 
                 {%if az_group_deployment_validate.input['mode'] %} --mode az_group_deployment_validate.input['mode'] {%endif %} 
                 {%if az_group_deployment_validate.input['parameters'] %} --parameters az_group_deployment_validate.input['parameters'] {%endif %} 
                 {%if az_group_deployment_validate.input['template-file'] %} --template-file az_group_deployment_validate.input['template-file'] {%endif %} 
                 {%if az_group_deployment_validate.input['template-uri'] %} --template-uri az_group_deployment_validate.input['template-uri'] {%endif %} 
   register: output  
 - set_fact: 
    az_group_deployment_validate: "{{ az_group_deployment_validate|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_group_deployment_validate }}" 
