

 - name: Set input params for az_group_deployment_list
   set_fact: 
     az_group_deployment_list:
       input: 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
         ###  Optional parameter. The filter to apply on the operation. For example, you can use $filter=provisioningState eq '{state}'.  ### 
        'filter': "{{ item['filter'] | default('') }}" 
         ###  Optional parameter. The number of results to get. If null is passed, returns all deployments.  ### 
        'top': "{{ item['top'] | default('') }}" 
 - debug: msg="{{ az_group_deployment_list }}"          
 - name: "az group deployment list: Get all the deployments for a resource group." 
   command: |                                      
     az group deployment list                            
                 --resource-group {{ az_group_deployment_list.input['resource-group'] }} 
                 {%if az_group_deployment_list.input['filter'] %} --filter az_group_deployment_list.input['filter'] {%endif %} 
                 {%if az_group_deployment_list.input['top'] %} --top az_group_deployment_list.input['top'] {%endif %} 
   register: output  
 - set_fact: 
    az_group_deployment_list: "{{ az_group_deployment_list|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_group_deployment_list }}" 
