

 - name: Set input params for az_monitor_autoscale_settings_delete
   set_fact: 
     az_monitor_autoscale_settings_delete:
       input: 
         ###  Required parameter. The autoscale setting name.  ### 
        'name': "{{ item['name'] | default('') }}" 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
 - debug: msg="{{ az_monitor_autoscale_settings_delete }}"          
 - name: "az monitor autoscale-settings delete: Deletes and autoscale setting." 
   command: |                                      
     az monitor autoscale-settings delete                            
                 --name {{ az_monitor_autoscale_settings_delete.input['name'] }} 
                 --resource-group {{ az_monitor_autoscale_settings_delete.input['resource-group'] }} 
   register: output  
 - set_fact: 
    az_monitor_autoscale_settings_delete: "{{ az_monitor_autoscale_settings_delete|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_monitor_autoscale_settings_delete }}" 
