

 - name: Set input params for az_monitor_diagnostic_settings_update
   set_fact: 
     az_monitor_diagnostic_settings_update:
       input: 
         ###  Required parameter. The name of the diagnostic setting.  ### 
        'name': "{{ item['name'] | default('') }}" 
         ###  Required parameter. Name or ID of the target resource.  ### 
        'resource': "{{ item['resource'] | default('') }}" 
         ###  Optional parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
         ###  Optional parameter. Target resource provider namespace.  ### 
        'resource-namespace': "{{ item['resource-namespace'] | default('') }}" 
         ###  Optional parameter. Target resource parent path, if applicable.  ### 
        'resource-parent': "{{ item['resource-parent'] | default('') }}" 
         ###  Optional parameter. Target resource type. Can also accept namespace/type format (Ex: 'Microsoft.Compute/virtualMachines)').  ### 
        'resource-type': "{{ item['resource-type'] | default('') }}" 
         ###  Optional parameter. Add an object to a list of objects by specifying a path and key value pairs.  Example: --add property.listProperty <key=value, string or JSON string>.  ### 
        'add': "{{ item['add'] | default('') }}" 
         ###  Optional parameter. Remove a property or an element from a list.  Example: --remove property.list <indexToRemove> OR --remove propertyToRemove.  ### 
        'remove': "{{ item['remove'] | default('') }}" 
         ###  Optional parameter. Update an object by specifying a property path and value to set.  Example: --set property1.property2=<value>.  ### 
        'set': "{{ item['set'] | default('') }}" 
 - debug: msg="{{ az_monitor_diagnostic_settings_update }}"          
 - name: "az monitor diagnostic-settings update: Update diagnostic settings." 
   command: |                                      
     az monitor diagnostic-settings update                            
                 --name {{ az_monitor_diagnostic_settings_update.input['name'] }} 
                 --resource {{ az_monitor_diagnostic_settings_update.input['resource'] }} 
                 {%if az_monitor_diagnostic_settings_update.input['resource-group'] %} --resource-group az_monitor_diagnostic_settings_update.input['resource-group'] {%endif %} 
                 {%if az_monitor_diagnostic_settings_update.input['resource-namespace'] %} --resource-namespace az_monitor_diagnostic_settings_update.input['resource-namespace'] {%endif %} 
                 {%if az_monitor_diagnostic_settings_update.input['resource-parent'] %} --resource-parent az_monitor_diagnostic_settings_update.input['resource-parent'] {%endif %} 
                 {%if az_monitor_diagnostic_settings_update.input['resource-type'] %} --resource-type az_monitor_diagnostic_settings_update.input['resource-type'] {%endif %} 
                 {%if az_monitor_diagnostic_settings_update.input['add'] %} --add az_monitor_diagnostic_settings_update.input['add'] {%endif %} 
                 {%if az_monitor_diagnostic_settings_update.input['remove'] %} --remove az_monitor_diagnostic_settings_update.input['remove'] {%endif %} 
                 {%if az_monitor_diagnostic_settings_update.input['set'] %} --set az_monitor_diagnostic_settings_update.input['set'] {%endif %} 
   register: output  
 - set_fact: 
    az_monitor_diagnostic_settings_update: "{{ az_monitor_diagnostic_settings_update|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_monitor_diagnostic_settings_update }}" 
