

 - name: Set input params for az_monitor_autoscale_settings_show
   set_fact: 
     az_monitor_autoscale_settings_show:
       input: 
         ###  Required parameter. The autoscale setting name.  ### 
        'name': "{{ item['name'] | default('') }}" 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
 - debug: msg="{{ az_monitor_autoscale_settings_show }}"          
 - name: "az monitor autoscale-settings show: Gets an autoscale setting." 
   command: |                                      
     az monitor autoscale-settings show                            
                 --name {{ az_monitor_autoscale_settings_show.input['name'] }} 
                 --resource-group {{ az_monitor_autoscale_settings_show.input['resource-group'] }} 
   register: output  
 - set_fact: 
    az_monitor_autoscale_settings_show: "{{ az_monitor_autoscale_settings_show|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_monitor_autoscale_settings_show }}" 
