

 - name: Set input params for az_monitor_autoscale_settings_list
   set_fact: 
     az_monitor_autoscale_settings_list:
       input: 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
 - debug: msg="{{ az_monitor_autoscale_settings_list }}"          
 - name: "az monitor autoscale-settings list: Lists the autoscale settings for a resource group." 
   command: |                                      
     az monitor autoscale-settings list                            
                 --resource-group {{ az_monitor_autoscale_settings_list.input['resource-group'] }} 
   register: output  
 - set_fact: 
    az_monitor_autoscale_settings_list: "{{ az_monitor_autoscale_settings_list|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_monitor_autoscale_settings_list }}" 
