

 - name: Set input params for az_mysql_server_configuration_list
   set_fact: 
     az_mysql_server_configuration_list:
       input: 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
         ###  Required parameter. Name of the server.  ### 
        'server-name': "{{ item['server-name'] | default('') }}" 
 - debug: msg="{{ az_mysql_server_configuration_list }}"          
 - name: "az mysql server configuration list: List the configuration values for a server." 
   command: |                                      
     az mysql server configuration list                            
                 --resource-group {{ az_mysql_server_configuration_list.input['resource-group'] }} 
                 --server-name {{ az_mysql_server_configuration_list.input['server-name'] }} 
   register: output  
 - set_fact: 
    az_mysql_server_configuration_list: "{{ az_mysql_server_configuration_list|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_mysql_server_configuration_list }}" 
