

 - name: Set input params for az_mysql_server_configuration_set
   set_fact: 
     az_mysql_server_configuration_set:
       input: 
         ###  Required parameter. The name of the server configuration.  ### 
        'name': "{{ item['name'] | default('') }}" 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
         ###  Required parameter. Name of the server.  ### 
        'server-name': "{{ item['server-name'] | default('') }}" 
         ###  Optional parameter. Value of the configuration. If not provided, configuration value will be set to default.  ### 
        'value': "{{ item['value'] | default('') }}" 
 - debug: msg="{{ az_mysql_server_configuration_set }}"          
 - name: "az mysql server configuration set: Update the configuration of a server." 
   command: |                                      
     az mysql server configuration set                            
                 --name {{ az_mysql_server_configuration_set.input['name'] }} 
                 --resource-group {{ az_mysql_server_configuration_set.input['resource-group'] }} 
                 --server-name {{ az_mysql_server_configuration_set.input['server-name'] }} 
                 {%if az_mysql_server_configuration_set.input['value'] %} --value az_mysql_server_configuration_set.input['value'] {%endif %} 
   register: output  
 - set_fact: 
    az_mysql_server_configuration_set: "{{ az_mysql_server_configuration_set|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_mysql_server_configuration_set }}" 
