

 - name: Set input params for az_mysql_server_configuration_show
   set_fact: 
     az_mysql_server_configuration_show:
       input: 
         ###  Required parameter. The name of the server configuration to be retrieved.  ### 
        'name': "{{ item['name'] | default('') }}" 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
         ###  Required parameter. Name of the server.  ### 
        'server-name': "{{ item['server-name'] | default('') }}" 
 - debug: msg="{{ az_mysql_server_configuration_show }}"          
 - name: "az mysql server configuration show: Get the configuration for a server."." 
   command: |                                      
     az mysql server configuration show                            
                 --name {{ az_mysql_server_configuration_show.input['name'] }} 
                 --resource-group {{ az_mysql_server_configuration_show.input['resource-group'] }} 
                 --server-name {{ az_mysql_server_configuration_show.input['server-name'] }} 
   register: output  
 - set_fact: 
    az_mysql_server_configuration_show: "{{ az_mysql_server_configuration_show|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_mysql_server_configuration_show }}" 
