

 - name: Set input params for az_network_application_gateway_ssl_policy_set
   set_fact: 
     az_network_application_gateway_ssl_policy_set:
       input: 
         ###  Required parameter. The name of the application gateway.  ### 
        'gateway-name': "{{ item['gateway-name'] | default('') }}" 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
         ###  Optional parameter. Ssl cipher suites to be enabled in the specified order to application gateway.  ### 
        'cipher-suites': "{{ item['cipher-suites'] | default('') }}" 
         ###  Optional parameter. Space separated list of protocols to disable.  ### 
        'disabled-ssl-protocols': "{{ item['disabled-ssl-protocols'] | default('') }}" 
         ###  Optional parameter. Minimum version of Ssl protocol to be supported on application gateway.  ### 
        'min-protocol-version': "{{ item['min-protocol-version'] | default('') }}" 
         ###  Optional parameter. Name of Ssl predefined policy.  ### 
        'name': "{{ item['name'] | default('') }}" 
         ###  Optional parameter. Do not wait for the long-running operation to finish.  ### 
        'no-wait': "{{ item['no-wait'] | default('') }}" 
         ###  Optional parameter. Type of Ssl Policy.  ### 
        'policy-type': "{{ item['policy-type'] | default('') }}" 
 - debug: msg="{{ az_network_application_gateway_ssl_policy_set }}"          
 - name: "az network application-gateway ssl-policy set: Update or clear SSL policy settings." 
   command: |                                      
     az network application-gateway ssl-policy set                            
                 --gateway-name {{ az_network_application_gateway_ssl_policy_set.input['gateway-name'] }} 
                 --resource-group {{ az_network_application_gateway_ssl_policy_set.input['resource-group'] }} 
                 {%if az_network_application_gateway_ssl_policy_set.input['cipher-suites'] %} --cipher-suites az_network_application_gateway_ssl_policy_set.input['cipher-suites'] {%endif %} 
                 {%if az_network_application_gateway_ssl_policy_set.input['disabled-ssl-protocols'] %} --disabled-ssl-protocols az_network_application_gateway_ssl_policy_set.input['disabled-ssl-protocols'] {%endif %} 
                 {%if az_network_application_gateway_ssl_policy_set.input['min-protocol-version'] %} --min-protocol-version az_network_application_gateway_ssl_policy_set.input['min-protocol-version'] {%endif %} 
                 {%if az_network_application_gateway_ssl_policy_set.input['name'] %} --name az_network_application_gateway_ssl_policy_set.input['name'] {%endif %} 
                 {%if az_network_application_gateway_ssl_policy_set.input['no-wait'] %} --no-wait az_network_application_gateway_ssl_policy_set.input['no-wait'] {%endif %} 
                 {%if az_network_application_gateway_ssl_policy_set.input['policy-type'] %} --policy-type az_network_application_gateway_ssl_policy_set.input['policy-type'] {%endif %} 
   register: output  
 - set_fact: 
    az_network_application_gateway_ssl_policy_set: "{{ az_network_application_gateway_ssl_policy_set|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_network_application_gateway_ssl_policy_set }}" 
