

 - name: Set input params for az_network_vnet_gateway_list_learned_routes
   set_fact: 
     az_network_vnet_gateway_list_learned_routes:
       input: 
         ###  Required parameter. Name of the VNet gateway.  ### 
        'name': "{{ item['name'] | default('') }}" 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
 - debug: msg="{{ az_network_vnet_gateway_list_learned_routes }}"          
 - name: "az network vnet-gateway list-learned-routes: This operation retrieves a list of routes the virtual network gateway has learned, including routes learned from BGP peers." 
   command: |                                      
     az network vnet-gateway list-learned-routes                            
                 --name {{ az_network_vnet_gateway_list_learned_routes.input['name'] }} 
                 --resource-group {{ az_network_vnet_gateway_list_learned_routes.input['resource-group'] }} 
   register: output  
 - set_fact: 
    az_network_vnet_gateway_list_learned_routes: "{{ az_network_vnet_gateway_list_learned_routes|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_network_vnet_gateway_list_learned_routes }}" 
