

 - name: Set input params for az_network_nic_ip_config_list
   set_fact: 
     az_network_nic_ip_config_list:
       input: 
         ###  Required parameter. The network interface (NIC).  ### 
        'nic-name': "{{ item['nic-name'] | default('') }}" 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
 - debug: msg="{{ az_network_nic_ip_config_list }}"          
 - name: "az network nic ip-config list: List IP configurations." 
   command: |                                      
     az network nic ip-config list                            
                 --nic-name {{ az_network_nic_ip_config_list.input['nic-name'] }} 
                 --resource-group {{ az_network_nic_ip_config_list.input['resource-group'] }} 
   register: output  
 - set_fact: 
    az_network_nic_ip_config_list: "{{ az_network_nic_ip_config_list|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_network_nic_ip_config_list }}" 
