

 - name: Set input params for az_network_application_gateway_http_settings_update
   set_fact: 
     az_network_application_gateway_http_settings_update:
       input: 
         ###  Required parameter. The name of the application gateway.  ### 
        'gateway-name': "{{ item['gateway-name'] | default('') }}" 
         ###  Required parameter. The name of the backed HTTP settings.  ### 
        'name': "{{ item['name'] | default('') }}" 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
         ###  Optional parameter. Name used for the affinity cookie.  ### 
        'affinity-cookie-name': "{{ item['affinity-cookie-name'] | default('') }}" 
         ###  Optional parameter. The time in seconds after a backend server is removed during which on open connection remains active. Range: 0 (disabled) to 3600.  ### 
        'connection-draining-timeout': "{{ item['connection-draining-timeout'] | default('') }}" 
         ###  Optional parameter. Enable or disable cookie-based affinity.  ### 
        'cookie-based-affinity': "{{ item['cookie-based-affinity'] | default('') }}" 
         ###  Optional parameter. Whether the probe is enabled.  ### 
        'enable-probe': "{{ item['enable-probe'] | default('') }}" 
         ###  Optional parameter. Host header sent to the backend servers.  ### 
        'host-name': "{{ item['host-name'] | default('') }}" 
         ###  Optional parameter. Use host name of the backend server as the host header.  ### 
        'host-name-from-backend-pool': "{{ item['host-name-from-backend-pool'] | default('') }}" 
         ###  Optional parameter. Do not wait for the long-running operation to finish.  ### 
        'no-wait': "{{ item['no-wait'] | default('') }}" 
         ###  Optional parameter. Path that will prefix all HTTP requests.  ### 
        'path': "{{ item['path'] | default('') }}" 
         ###  Optional parameter. The port number.  ### 
        'port': "{{ item['port'] | default('') }}" 
         ###  Optional parameter. Name or ID of the probe to associate with the HTTP settings.  ### 
        'probe': "{{ item['probe'] | default('') }}" 
         ###  Optional parameter. The HTTP settings protocol.  ### 
        'protocol': "{{ item['protocol'] | default('') }}" 
         ###  Optional parameter. Request timeout in seconds.  ### 
        'timeout': "{{ item['timeout'] | default('') }}" 
         ###  Optional parameter. Add an object to a list of objects by specifying a path and key value pairs.  Example: --add property.listProperty <key=value, string or JSON string>.  ### 
        'add': "{{ item['add'] | default('') }}" 
         ###  Optional parameter. Remove a property or an element from a list.  Example: --remove property.list <indexToRemove> OR --remove propertyToRemove.  ### 
        'remove': "{{ item['remove'] | default('') }}" 
         ###  Optional parameter. Update an object by specifying a property path and value to set.  Example: --set property1.property2=<value>.  ### 
        'set': "{{ item['set'] | default('') }}" 
 - debug: msg="{{ az_network_application_gateway_http_settings_update }}"          
 - name: "az network application-gateway http-settings update: Update HTTP settings." 
   command: |                                      
     az network application-gateway http-settings update                            
                 --gateway-name {{ az_network_application_gateway_http_settings_update.input['gateway-name'] }} 
                 --name {{ az_network_application_gateway_http_settings_update.input['name'] }} 
                 --resource-group {{ az_network_application_gateway_http_settings_update.input['resource-group'] }} 
                 {%if az_network_application_gateway_http_settings_update.input['affinity-cookie-name'] %} --affinity-cookie-name az_network_application_gateway_http_settings_update.input['affinity-cookie-name'] {%endif %} 
                 {%if az_network_application_gateway_http_settings_update.input['connection-draining-timeout'] %} --connection-draining-timeout az_network_application_gateway_http_settings_update.input['connection-draining-timeout'] {%endif %} 
                 {%if az_network_application_gateway_http_settings_update.input['cookie-based-affinity'] %} --cookie-based-affinity az_network_application_gateway_http_settings_update.input['cookie-based-affinity'] {%endif %} 
                 {%if az_network_application_gateway_http_settings_update.input['enable-probe'] %} --enable-probe az_network_application_gateway_http_settings_update.input['enable-probe'] {%endif %} 
                 {%if az_network_application_gateway_http_settings_update.input['host-name'] %} --host-name az_network_application_gateway_http_settings_update.input['host-name'] {%endif %} 
                 {%if az_network_application_gateway_http_settings_update.input['host-name-from-backend-pool'] %} --host-name-from-backend-pool az_network_application_gateway_http_settings_update.input['host-name-from-backend-pool'] {%endif %} 
                 {%if az_network_application_gateway_http_settings_update.input['no-wait'] %} --no-wait az_network_application_gateway_http_settings_update.input['no-wait'] {%endif %} 
                 {%if az_network_application_gateway_http_settings_update.input['path'] %} --path az_network_application_gateway_http_settings_update.input['path'] {%endif %} 
                 {%if az_network_application_gateway_http_settings_update.input['port'] %} --port az_network_application_gateway_http_settings_update.input['port'] {%endif %} 
                 {%if az_network_application_gateway_http_settings_update.input['probe'] %} --probe az_network_application_gateway_http_settings_update.input['probe'] {%endif %} 
                 {%if az_network_application_gateway_http_settings_update.input['protocol'] %} --protocol az_network_application_gateway_http_settings_update.input['protocol'] {%endif %} 
                 {%if az_network_application_gateway_http_settings_update.input['timeout'] %} --timeout az_network_application_gateway_http_settings_update.input['timeout'] {%endif %} 
                 {%if az_network_application_gateway_http_settings_update.input['add'] %} --add az_network_application_gateway_http_settings_update.input['add'] {%endif %} 
                 {%if az_network_application_gateway_http_settings_update.input['remove'] %} --remove az_network_application_gateway_http_settings_update.input['remove'] {%endif %} 
                 {%if az_network_application_gateway_http_settings_update.input['set'] %} --set az_network_application_gateway_http_settings_update.input['set'] {%endif %} 
   register: output  
 - set_fact: 
    az_network_application_gateway_http_settings_update: "{{ az_network_application_gateway_http_settings_update|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_network_application_gateway_http_settings_update }}" 
