

 - name: Set input params for az_network_nic_ip_config_delete
   set_fact: 
     az_network_nic_ip_config_delete:
       input: 
         ###  Required parameter. The name of the IP configuration.  ### 
        'name': "{{ item['name'] | default('') }}" 
         ###  Required parameter. The network interface (NIC).  ### 
        'nic-name': "{{ item['nic-name'] | default('') }}" 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
         ###  Optional parameter.   ### 
        'no-wait': "{{ item['no-wait'] | default('') }}" 
 - debug: msg="{{ az_network_nic_ip_config_delete }}"          
 - name: "az network nic ip-config delete: Delete an IP configuration." 
   command: |                                      
     az network nic ip-config delete                            
                 --name {{ az_network_nic_ip_config_delete.input['name'] }} 
                 --nic-name {{ az_network_nic_ip_config_delete.input['nic-name'] }} 
                 --resource-group {{ az_network_nic_ip_config_delete.input['resource-group'] }} 
                 {%if az_network_nic_ip_config_delete.input['no-wait'] %} --no-wait az_network_nic_ip_config_delete.input['no-wait'] {%endif %} 
   register: output  
 - set_fact: 
    az_network_nic_ip_config_delete: "{{ az_network_nic_ip_config_delete|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_network_nic_ip_config_delete }}" 
