

 - name: Set input params for az_network_nic_ip_config_update
   set_fact: 
     az_network_nic_ip_config_update:
       input: 
         ###  Required parameter. The name of the IP configuration.  ### 
        'name': "{{ item['name'] | default('') }}" 
         ###  Required parameter. The network interface (NIC).  ### 
        'nic-name': "{{ item['nic-name'] | default('') }}" 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
         ###  Optional parameter. Space separated list of application security groups.  ### 
        'application-security-groups': "{{ item['application-security-groups'] | default('') }}" 
         ###  Optional parameter. Space separated list of names or IDs of load balancer address pools to associate with the NIC. If names are used, --lb-name must be specified.  ### 
        'lb-address-pools': "{{ item['lb-address-pools'] | default('') }}" 
         ###  Optional parameter. Space separated list of names or IDs of load balancer inbound NAT rules to associate with the NIC. If names are used, --lb-name must be specified.  ### 
        'lb-inbound-nat-rules': "{{ item['lb-inbound-nat-rules'] | default('') }}" 
         ###  Optional parameter. The name of the load balancer to use when adding NAT rules or address pools by name (ignored when IDs are specified).  ### 
        'lb-name': "{{ item['lb-name'] | default('') }}" 
         ###  Optional parameter. Set to make this configuration the primary one for the NIC.  ### 
        'make-primary': "{{ item['make-primary'] | default('') }}" 
         ###  Optional parameter. Static private IP address to use.  ### 
        'private-ip-address': "{{ item['private-ip-address'] | default('') }}" 
         ###  Optional parameter.   ### 
        'private-ip-address-version': "{{ item['private-ip-address-version'] | default('') }}" 
         ###  Optional parameter. Name or ID of the public IP to use.  ### 
        'public-ip-address': "{{ item['public-ip-address'] | default('') }}" 
         ###  Optional parameter. Name or ID of an existing subnet. If name is specified, also specify --vnet-name.  ### 
        'subnet': "{{ item['subnet'] | default('') }}" 
         ###  Optional parameter. The virtual network (VNet) associated with the subnet (Omit if supplying a subnet id).  ### 
        'vnet-name': "{{ item['vnet-name'] | default('') }}" 
         ###  Optional parameter. Add an object to a list of objects by specifying a path and key value pairs.  Example: --add property.listProperty <key=value, string or JSON string>.  ### 
        'add': "{{ item['add'] | default('') }}" 
         ###  Optional parameter. Remove a property or an element from a list.  Example: --remove property.list <indexToRemove> OR --remove propertyToRemove.  ### 
        'remove': "{{ item['remove'] | default('') }}" 
         ###  Optional parameter. Update an object by specifying a property path and value to set.  Example: --set property1.property2=<value>.  ### 
        'set': "{{ item['set'] | default('') }}" 
 - debug: msg="{{ az_network_nic_ip_config_update }}"          
 - name: "az network nic ip-config update: Update an IP configuration." 
   command: |                                      
     az network nic ip-config update                            
                 --name {{ az_network_nic_ip_config_update.input['name'] }} 
                 --nic-name {{ az_network_nic_ip_config_update.input['nic-name'] }} 
                 --resource-group {{ az_network_nic_ip_config_update.input['resource-group'] }} 
                 {%if az_network_nic_ip_config_update.input['application-security-groups'] %} --application-security-groups az_network_nic_ip_config_update.input['application-security-groups'] {%endif %} 
                 {%if az_network_nic_ip_config_update.input['lb-address-pools'] %} --lb-address-pools az_network_nic_ip_config_update.input['lb-address-pools'] {%endif %} 
                 {%if az_network_nic_ip_config_update.input['lb-inbound-nat-rules'] %} --lb-inbound-nat-rules az_network_nic_ip_config_update.input['lb-inbound-nat-rules'] {%endif %} 
                 {%if az_network_nic_ip_config_update.input['lb-name'] %} --lb-name az_network_nic_ip_config_update.input['lb-name'] {%endif %} 
                 {%if az_network_nic_ip_config_update.input['make-primary'] %} --make-primary az_network_nic_ip_config_update.input['make-primary'] {%endif %} 
                 {%if az_network_nic_ip_config_update.input['private-ip-address'] %} --private-ip-address az_network_nic_ip_config_update.input['private-ip-address'] {%endif %} 
                 {%if az_network_nic_ip_config_update.input['private-ip-address-version'] %} --private-ip-address-version az_network_nic_ip_config_update.input['private-ip-address-version'] {%endif %} 
                 {%if az_network_nic_ip_config_update.input['public-ip-address'] %} --public-ip-address az_network_nic_ip_config_update.input['public-ip-address'] {%endif %} 
                 {%if az_network_nic_ip_config_update.input['subnet'] %} --subnet az_network_nic_ip_config_update.input['subnet'] {%endif %} 
                 {%if az_network_nic_ip_config_update.input['vnet-name'] %} --vnet-name az_network_nic_ip_config_update.input['vnet-name'] {%endif %} 
                 {%if az_network_nic_ip_config_update.input['add'] %} --add az_network_nic_ip_config_update.input['add'] {%endif %} 
                 {%if az_network_nic_ip_config_update.input['remove'] %} --remove az_network_nic_ip_config_update.input['remove'] {%endif %} 
                 {%if az_network_nic_ip_config_update.input['set'] %} --set az_network_nic_ip_config_update.input['set'] {%endif %} 
   register: output  
 - set_fact: 
    az_network_nic_ip_config_update: "{{ az_network_nic_ip_config_update|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_network_nic_ip_config_update }}" 
