

 - name: Set input params for az_network_application_gateway_address_pool_create
   set_fact: 
     az_network_application_gateway_address_pool_create:
       input: 
         ###  Required parameter. The name of the application gateway.  ### 
        'gateway-name': "{{ item['gateway-name'] | default('') }}" 
         ###  Required parameter. The name of the backend address pool.  ### 
        'name': "{{ item['name'] | default('') }}" 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
         ###  Optional parameter. Do not wait for the long-running operation to finish.  ### 
        'no-wait': "{{ item['no-wait'] | default('') }}" 
         ###  Optional parameter. Space separated list of IP addresses or DNS names corresponding to backend servers.  ### 
        'servers': "{{ item['servers'] | default('') }}" 
 - debug: msg="{{ az_network_application_gateway_address_pool_create }}"          
 - name: "az network application-gateway address-pool create: Create a backend address pool." 
   command: |                                      
     az network application-gateway address-pool create                            
                 --gateway-name {{ az_network_application_gateway_address_pool_create.input['gateway-name'] }} 
                 --name {{ az_network_application_gateway_address_pool_create.input['name'] }} 
                 --resource-group {{ az_network_application_gateway_address_pool_create.input['resource-group'] }} 
                 {%if az_network_application_gateway_address_pool_create.input['no-wait'] %} --no-wait az_network_application_gateway_address_pool_create.input['no-wait'] {%endif %} 
                 {%if az_network_application_gateway_address_pool_create.input['servers'] %} --servers az_network_application_gateway_address_pool_create.input['servers'] {%endif %} 
   register: output  
 - set_fact: 
    az_network_application_gateway_address_pool_create: "{{ az_network_application_gateway_address_pool_create|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_network_application_gateway_address_pool_create }}" 
