

 - name: Set input params for az_network_application_gateway_rule_show
   set_fact: 
     az_network_application_gateway_rule_show:
       input: 
         ###  Required parameter. The name of the application gateway.  ### 
        'gateway-name': "{{ item['gateway-name'] | default('') }}" 
         ###  Required parameter. The name of the request routing rule.  ### 
        'name': "{{ item['name'] | default('') }}" 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
 - debug: msg="{{ az_network_application_gateway_rule_show }}"          
 - name: "az network application-gateway rule show: Get the details of a rule." 
   command: |                                      
     az network application-gateway rule show                            
                 --gateway-name {{ az_network_application_gateway_rule_show.input['gateway-name'] }} 
                 --name {{ az_network_application_gateway_rule_show.input['name'] }} 
                 --resource-group {{ az_network_application_gateway_rule_show.input['resource-group'] }} 
   register: output  
 - set_fact: 
    az_network_application_gateway_rule_show: "{{ az_network_application_gateway_rule_show|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_network_application_gateway_rule_show }}" 
