

 - name: Set input params for az_network_application_gateway_url_path_map_list
   set_fact: 
     az_network_application_gateway_url_path_map_list:
       input: 
         ###  Required parameter. The name of the application gateway.  ### 
        'gateway-name': "{{ item['gateway-name'] | default('') }}" 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
 - debug: msg="{{ az_network_application_gateway_url_path_map_list }}"          
 - name: "az network application-gateway url-path-map list: List URL path maps." 
   command: |                                      
     az network application-gateway url-path-map list                            
                 --gateway-name {{ az_network_application_gateway_url_path_map_list.input['gateway-name'] }} 
                 --resource-group {{ az_network_application_gateway_url_path_map_list.input['resource-group'] }} 
   register: output  
 - set_fact: 
    az_network_application_gateway_url_path_map_list: "{{ az_network_application_gateway_url_path_map_list|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_network_application_gateway_url_path_map_list }}" 
