

 - name: Set input params for az_network_application_gateway_rule_update
   set_fact: 
     az_network_application_gateway_rule_update:
       input: 
         ###  Required parameter. The name of the application gateway.  ### 
        'gateway-name': "{{ item['gateway-name'] | default('') }}" 
         ###  Required parameter. The name of the request routing rule.  ### 
        'name': "{{ item['name'] | default('') }}" 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
         ###  Optional parameter. The name or ID of the backend address pool.  ### 
        'address-pool': "{{ item['address-pool'] | default('') }}" 
         ###  Optional parameter. The name or ID of the HTTP listener.  ### 
        'http-listener': "{{ item['http-listener'] | default('') }}" 
         ###  Optional parameter. The name or ID of the backend HTTP settings.  ### 
        'http-settings': "{{ item['http-settings'] | default('') }}" 
         ###  Optional parameter. Do not wait for the long-running operation to finish.  ### 
        'no-wait': "{{ item['no-wait'] | default('') }}" 
         ###  Optional parameter. The name or ID of the redirect configuration to use with the created rule.  ### 
        'redirect-config': "{{ item['redirect-config'] | default('') }}" 
         ###  Optional parameter. The rule type (Basic, PathBasedRouting).  ### 
        'rule-type': "{{ item['rule-type'] | default('') }}" 
         ###  Optional parameter. The name or ID of the URL path map.  ### 
        'url-path-map': "{{ item['url-path-map'] | default('') }}" 
         ###  Optional parameter. Add an object to a list of objects by specifying a path and key value pairs.  Example: --add property.listProperty <key=value, string or JSON string>.  ### 
        'add': "{{ item['add'] | default('') }}" 
         ###  Optional parameter. Remove a property or an element from a list.  Example: --remove property.list <indexToRemove> OR --remove propertyToRemove.  ### 
        'remove': "{{ item['remove'] | default('') }}" 
         ###  Optional parameter. Update an object by specifying a property path and value to set.  Example: --set property1.property2=<value>.  ### 
        'set': "{{ item['set'] | default('') }}" 
 - debug: msg="{{ az_network_application_gateway_rule_update }}"          
 - name: "az network application-gateway rule update: Update a rule." 
   command: |                                      
     az network application-gateway rule update                            
                 --gateway-name {{ az_network_application_gateway_rule_update.input['gateway-name'] }} 
                 --name {{ az_network_application_gateway_rule_update.input['name'] }} 
                 --resource-group {{ az_network_application_gateway_rule_update.input['resource-group'] }} 
                 {%if az_network_application_gateway_rule_update.input['address-pool'] %} --address-pool az_network_application_gateway_rule_update.input['address-pool'] {%endif %} 
                 {%if az_network_application_gateway_rule_update.input['http-listener'] %} --http-listener az_network_application_gateway_rule_update.input['http-listener'] {%endif %} 
                 {%if az_network_application_gateway_rule_update.input['http-settings'] %} --http-settings az_network_application_gateway_rule_update.input['http-settings'] {%endif %} 
                 {%if az_network_application_gateway_rule_update.input['no-wait'] %} --no-wait az_network_application_gateway_rule_update.input['no-wait'] {%endif %} 
                 {%if az_network_application_gateway_rule_update.input['redirect-config'] %} --redirect-config az_network_application_gateway_rule_update.input['redirect-config'] {%endif %} 
                 {%if az_network_application_gateway_rule_update.input['rule-type'] %} --rule-type az_network_application_gateway_rule_update.input['rule-type'] {%endif %} 
                 {%if az_network_application_gateway_rule_update.input['url-path-map'] %} --url-path-map az_network_application_gateway_rule_update.input['url-path-map'] {%endif %} 
                 {%if az_network_application_gateway_rule_update.input['add'] %} --add az_network_application_gateway_rule_update.input['add'] {%endif %} 
                 {%if az_network_application_gateway_rule_update.input['remove'] %} --remove az_network_application_gateway_rule_update.input['remove'] {%endif %} 
                 {%if az_network_application_gateway_rule_update.input['set'] %} --set az_network_application_gateway_rule_update.input['set'] {%endif %} 
   register: output  
 - set_fact: 
    az_network_application_gateway_rule_update: "{{ az_network_application_gateway_rule_update|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_network_application_gateway_rule_update }}" 
