

 - name: Set input params for az_network_application_gateway_probe_update
   set_fact: 
     az_network_application_gateway_probe_update:
       input: 
         ###  Required parameter. The name of the application gateway.  ### 
        'gateway-name': "{{ item['gateway-name'] | default('') }}" 
         ###  Required parameter. The name of the probe.  ### 
        'name': "{{ item['name'] | default('') }}" 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
         ###  Optional parameter. The name of the host to send the probe.  ### 
        'host': "{{ item['host'] | default('') }}" 
         ###  Optional parameter. Use host header from HTTP settings.  ### 
        'host-name-from-http-settings': "{{ item['host-name-from-http-settings'] | default('') }}" 
         ###  Optional parameter. The time interval in seconds between consecutive probes.  ### 
        'interval': "{{ item['interval'] | default('') }}" 
         ###  Optional parameter. Body that must be contained in the health response.  ### 
        'match-body': "{{ item['match-body'] | default('') }}" 
         ###  Optional parameter. Space-separated list of allowed ranges of healthy status codes for the health response.  ### 
        'match-status-codes': "{{ item['match-status-codes'] | default('') }}" 
         ###  Optional parameter. Minimum number of servers that are always marked healthy.  ### 
        'min-servers': "{{ item['min-servers'] | default('') }}" 
         ###  Optional parameter. Do not wait for the long-running operation to finish.  ### 
        'no-wait': "{{ item['no-wait'] | default('') }}" 
         ###  Optional parameter. The relative path of the probe. Valid paths start from "/".  ### 
        'path': "{{ item['path'] | default('') }}" 
         ###  Optional parameter. The HTTP settings protocol.  ### 
        'protocol': "{{ item['protocol'] | default('') }}" 
         ###  Optional parameter. The number of failed probes after which the back end server is marked down.  ### 
        'threshold': "{{ item['threshold'] | default('') }}" 
         ###  Optional parameter. The probe timeout in seconds.  ### 
        'timeout': "{{ item['timeout'] | default('') }}" 
         ###  Optional parameter. Add an object to a list of objects by specifying a path and key value pairs.  Example: --add property.listProperty <key=value, string or JSON string>.  ### 
        'add': "{{ item['add'] | default('') }}" 
         ###  Optional parameter. Remove a property or an element from a list.  Example: --remove property.list <indexToRemove> OR --remove propertyToRemove.  ### 
        'remove': "{{ item['remove'] | default('') }}" 
         ###  Optional parameter. Update an object by specifying a property path and value to set.  Example: --set property1.property2=<value>.  ### 
        'set': "{{ item['set'] | default('') }}" 
 - debug: msg="{{ az_network_application_gateway_probe_update }}"          
 - name: "az network application-gateway probe update: Update a probe." 
   command: |                                      
     az network application-gateway probe update                            
                 --gateway-name {{ az_network_application_gateway_probe_update.input['gateway-name'] }} 
                 --name {{ az_network_application_gateway_probe_update.input['name'] }} 
                 --resource-group {{ az_network_application_gateway_probe_update.input['resource-group'] }} 
                 {%if az_network_application_gateway_probe_update.input['host'] %} --host az_network_application_gateway_probe_update.input['host'] {%endif %} 
                 {%if az_network_application_gateway_probe_update.input['host-name-from-http-settings'] %} --host-name-from-http-settings az_network_application_gateway_probe_update.input['host-name-from-http-settings'] {%endif %} 
                 {%if az_network_application_gateway_probe_update.input['interval'] %} --interval az_network_application_gateway_probe_update.input['interval'] {%endif %} 
                 {%if az_network_application_gateway_probe_update.input['match-body'] %} --match-body az_network_application_gateway_probe_update.input['match-body'] {%endif %} 
                 {%if az_network_application_gateway_probe_update.input['match-status-codes'] %} --match-status-codes az_network_application_gateway_probe_update.input['match-status-codes'] {%endif %} 
                 {%if az_network_application_gateway_probe_update.input['min-servers'] %} --min-servers az_network_application_gateway_probe_update.input['min-servers'] {%endif %} 
                 {%if az_network_application_gateway_probe_update.input['no-wait'] %} --no-wait az_network_application_gateway_probe_update.input['no-wait'] {%endif %} 
                 {%if az_network_application_gateway_probe_update.input['path'] %} --path az_network_application_gateway_probe_update.input['path'] {%endif %} 
                 {%if az_network_application_gateway_probe_update.input['protocol'] %} --protocol az_network_application_gateway_probe_update.input['protocol'] {%endif %} 
                 {%if az_network_application_gateway_probe_update.input['threshold'] %} --threshold az_network_application_gateway_probe_update.input['threshold'] {%endif %} 
                 {%if az_network_application_gateway_probe_update.input['timeout'] %} --timeout az_network_application_gateway_probe_update.input['timeout'] {%endif %} 
                 {%if az_network_application_gateway_probe_update.input['add'] %} --add az_network_application_gateway_probe_update.input['add'] {%endif %} 
                 {%if az_network_application_gateway_probe_update.input['remove'] %} --remove az_network_application_gateway_probe_update.input['remove'] {%endif %} 
                 {%if az_network_application_gateway_probe_update.input['set'] %} --set az_network_application_gateway_probe_update.input['set'] {%endif %} 
   register: output  
 - set_fact: 
    az_network_application_gateway_probe_update: "{{ az_network_application_gateway_probe_update|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_network_application_gateway_probe_update }}" 
