

 - name: Set input params for az_network_application_gateway_redirect_config_list
   set_fact: 
     az_network_application_gateway_redirect_config_list:
       input: 
         ###  Required parameter. The name of the application gateway.  ### 
        'gateway-name': "{{ item['gateway-name'] | default('') }}" 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
 - debug: msg="{{ az_network_application_gateway_redirect_config_list }}"          
 - name: "az network application-gateway redirect-config list: List redirect configurations." 
   command: |                                      
     az network application-gateway redirect-config list                            
                 --gateway-name {{ az_network_application_gateway_redirect_config_list.input['gateway-name'] }} 
                 --resource-group {{ az_network_application_gateway_redirect_config_list.input['resource-group'] }} 
   register: output  
 - set_fact: 
    az_network_application_gateway_redirect_config_list: "{{ az_network_application_gateway_redirect_config_list|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_network_application_gateway_redirect_config_list }}" 
