

 - name: Set input params for az_network_nic_ip_config_show
   set_fact: 
     az_network_nic_ip_config_show:
       input: 
         ###  Required parameter. The name of the IP configuration.  ### 
        'name': "{{ item['name'] | default('') }}" 
         ###  Required parameter. The network interface (NIC).  ### 
        'nic-name': "{{ item['nic-name'] | default('') }}" 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
 - debug: msg="{{ az_network_nic_ip_config_show }}"          
 - name: "az network nic ip-config show: Get the details of an IP configuration." 
   command: |                                      
     az network nic ip-config show                            
                 --name {{ az_network_nic_ip_config_show.input['name'] }} 
                 --nic-name {{ az_network_nic_ip_config_show.input['nic-name'] }} 
                 --resource-group {{ az_network_nic_ip_config_show.input['resource-group'] }} 
   register: output  
 - set_fact: 
    az_network_nic_ip_config_show: "{{ az_network_nic_ip_config_show|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_network_nic_ip_config_show }}" 
