

 - name: Set input params for az_network_application_gateway_url_path_map_update
   set_fact: 
     az_network_application_gateway_url_path_map_update:
       input: 
         ###  Required parameter. The name of the application gateway.  ### 
        'gateway-name': "{{ item['gateway-name'] | default('') }}" 
         ###  Required parameter. The name of the URL path map.  ### 
        'name': "{{ item['name'] | default('') }}" 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
         ###  Optional parameter. The name or ID of the default backend address pool.  ### 
        'default-address-pool': "{{ item['default-address-pool'] | default('') }}" 
         ###  Optional parameter. The name or ID of the default HTTP settings.  ### 
        'default-http-settings': "{{ item['default-http-settings'] | default('') }}" 
         ###  Optional parameter. The name or ID of the default redirect configuration.  ### 
        'default-redirect-config': "{{ item['default-redirect-config'] | default('') }}" 
         ###  Optional parameter. Do not wait for the long-running operation to finish.  ### 
        'no-wait': "{{ item['no-wait'] | default('') }}" 
         ###  Optional parameter. Add an object to a list of objects by specifying a path and key value pairs.  Example: --add property.listProperty <key=value, string or JSON string>.  ### 
        'add': "{{ item['add'] | default('') }}" 
         ###  Optional parameter. Remove a property or an element from a list.  Example: --remove property.list <indexToRemove> OR --remove propertyToRemove.  ### 
        'remove': "{{ item['remove'] | default('') }}" 
         ###  Optional parameter. Update an object by specifying a property path and value to set.  Example: --set property1.property2=<value>.  ### 
        'set': "{{ item['set'] | default('') }}" 
 - debug: msg="{{ az_network_application_gateway_url_path_map_update }}"          
 - name: "az network application-gateway url-path-map update: Update a URL path map." 
   command: |                                      
     az network application-gateway url-path-map update                            
                 --gateway-name {{ az_network_application_gateway_url_path_map_update.input['gateway-name'] }} 
                 --name {{ az_network_application_gateway_url_path_map_update.input['name'] }} 
                 --resource-group {{ az_network_application_gateway_url_path_map_update.input['resource-group'] }} 
                 {%if az_network_application_gateway_url_path_map_update.input['default-address-pool'] %} --default-address-pool az_network_application_gateway_url_path_map_update.input['default-address-pool'] {%endif %} 
                 {%if az_network_application_gateway_url_path_map_update.input['default-http-settings'] %} --default-http-settings az_network_application_gateway_url_path_map_update.input['default-http-settings'] {%endif %} 
                 {%if az_network_application_gateway_url_path_map_update.input['default-redirect-config'] %} --default-redirect-config az_network_application_gateway_url_path_map_update.input['default-redirect-config'] {%endif %} 
                 {%if az_network_application_gateway_url_path_map_update.input['no-wait'] %} --no-wait az_network_application_gateway_url_path_map_update.input['no-wait'] {%endif %} 
                 {%if az_network_application_gateway_url_path_map_update.input['add'] %} --add az_network_application_gateway_url_path_map_update.input['add'] {%endif %} 
                 {%if az_network_application_gateway_url_path_map_update.input['remove'] %} --remove az_network_application_gateway_url_path_map_update.input['remove'] {%endif %} 
                 {%if az_network_application_gateway_url_path_map_update.input['set'] %} --set az_network_application_gateway_url_path_map_update.input['set'] {%endif %} 
   register: output  
 - set_fact: 
    az_network_application_gateway_url_path_map_update: "{{ az_network_application_gateway_url_path_map_update|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_network_application_gateway_url_path_map_update }}" 
