

 - name: Set input params for az_network_application_gateway_http_listener_create
   set_fact: 
     az_network_application_gateway_http_listener_create:
       input: 
         ###  Required parameter. The name or ID of the frontend port.  ### 
        'frontend-port': "{{ item['frontend-port'] | default('') }}" 
         ###  Required parameter. The name of the application gateway.  ### 
        'gateway-name': "{{ item['gateway-name'] | default('') }}" 
         ###  Required parameter. The name of the HTTP listener.  ### 
        'name': "{{ item['name'] | default('') }}" 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
         ###  Optional parameter. The name or ID of the frontend IP configuration. If only one exists, omit to use as default.  ### 
        'frontend-ip': "{{ item['frontend-ip'] | default('') }}" 
         ###  Optional parameter. Host name to use for multisite gateways.  ### 
        'host-name': "{{ item['host-name'] | default('') }}" 
         ###  Optional parameter. Do not wait for the long-running operation to finish.  ### 
        'no-wait': "{{ item['no-wait'] | default('') }}" 
         ###  Optional parameter. The name or ID of the SSL certificate to use.  ### 
        'ssl-cert': "{{ item['ssl-cert'] | default('') }}" 
 - debug: msg="{{ az_network_application_gateway_http_listener_create }}"          
 - name: "az network application-gateway http-listener create: Create an HTTP listener." 
   command: |                                      
     az network application-gateway http-listener create                            
                 --frontend-port {{ az_network_application_gateway_http_listener_create.input['frontend-port'] }} 
                 --gateway-name {{ az_network_application_gateway_http_listener_create.input['gateway-name'] }} 
                 --name {{ az_network_application_gateway_http_listener_create.input['name'] }} 
                 --resource-group {{ az_network_application_gateway_http_listener_create.input['resource-group'] }} 
                 {%if az_network_application_gateway_http_listener_create.input['frontend-ip'] %} --frontend-ip az_network_application_gateway_http_listener_create.input['frontend-ip'] {%endif %} 
                 {%if az_network_application_gateway_http_listener_create.input['host-name'] %} --host-name az_network_application_gateway_http_listener_create.input['host-name'] {%endif %} 
                 {%if az_network_application_gateway_http_listener_create.input['no-wait'] %} --no-wait az_network_application_gateway_http_listener_create.input['no-wait'] {%endif %} 
                 {%if az_network_application_gateway_http_listener_create.input['ssl-cert'] %} --ssl-cert az_network_application_gateway_http_listener_create.input['ssl-cert'] {%endif %} 
   register: output  
 - set_fact: 
    az_network_application_gateway_http_listener_create: "{{ az_network_application_gateway_http_listener_create|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_network_application_gateway_http_listener_create }}" 
