

 - name: Set input params for az_network_application_gateway_rule_create
   set_fact: 
     az_network_application_gateway_rule_create:
       input: 
         ###  Required parameter. The name of the application gateway.  ### 
        'gateway-name': "{{ item['gateway-name'] | default('') }}" 
         ###  Required parameter. The name of the request routing rule.  ### 
        'name': "{{ item['name'] | default('') }}" 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
         ###  Optional parameter. The name or ID of the backend address pool. If only one exists, omit to use as default.  ### 
        'address-pool': "{{ item['address-pool'] | default('') }}" 
         ###  Optional parameter. The name or ID of the HTTP listener. If only one exists, omit to use as default.  ### 
        'http-listener': "{{ item['http-listener'] | default('') }}" 
         ###  Optional parameter. The name or ID of the HTTP settings. If only one exists, omit to use as default.  ### 
        'http-settings': "{{ item['http-settings'] | default('') }}" 
         ###  Optional parameter. Do not wait for the long-running operation to finish.  ### 
        'no-wait': "{{ item['no-wait'] | default('') }}" 
         ###  Optional parameter. The name or ID of the redirect configuration to use with the created rule.  ### 
        'redirect-config': "{{ item['redirect-config'] | default('') }}" 
         ###  Optional parameter. The rule type (Basic, PathBasedRouting).  ### 
        'rule-type': "{{ item['rule-type'] | default('') }}" 
         ###  Optional parameter. The name or ID of the URL path map.  ### 
        'url-path-map': "{{ item['url-path-map'] | default('') }}" 
 - debug: msg="{{ az_network_application_gateway_rule_create }}"          
 - name: "az network application-gateway rule create: Create a rule." 
   command: |                                      
     az network application-gateway rule create                            
                 --gateway-name {{ az_network_application_gateway_rule_create.input['gateway-name'] }} 
                 --name {{ az_network_application_gateway_rule_create.input['name'] }} 
                 --resource-group {{ az_network_application_gateway_rule_create.input['resource-group'] }} 
                 {%if az_network_application_gateway_rule_create.input['address-pool'] %} --address-pool az_network_application_gateway_rule_create.input['address-pool'] {%endif %} 
                 {%if az_network_application_gateway_rule_create.input['http-listener'] %} --http-listener az_network_application_gateway_rule_create.input['http-listener'] {%endif %} 
                 {%if az_network_application_gateway_rule_create.input['http-settings'] %} --http-settings az_network_application_gateway_rule_create.input['http-settings'] {%endif %} 
                 {%if az_network_application_gateway_rule_create.input['no-wait'] %} --no-wait az_network_application_gateway_rule_create.input['no-wait'] {%endif %} 
                 {%if az_network_application_gateway_rule_create.input['redirect-config'] %} --redirect-config az_network_application_gateway_rule_create.input['redirect-config'] {%endif %} 
                 {%if az_network_application_gateway_rule_create.input['rule-type'] %} --rule-type az_network_application_gateway_rule_create.input['rule-type'] {%endif %} 
                 {%if az_network_application_gateway_rule_create.input['url-path-map'] %} --url-path-map az_network_application_gateway_rule_create.input['url-path-map'] {%endif %} 
   register: output  
 - set_fact: 
    az_network_application_gateway_rule_create: "{{ az_network_application_gateway_rule_create|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_network_application_gateway_rule_create }}" 
