

 - name: Set input params for az_network_application_gateway_http_settings_delete
   set_fact: 
     az_network_application_gateway_http_settings_delete:
       input: 
         ###  Required parameter. The name of the application gateway.  ### 
        'gateway-name': "{{ item['gateway-name'] | default('') }}" 
         ###  Required parameter. The name of the backed HTTP settings.  ### 
        'name': "{{ item['name'] | default('') }}" 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
         ###  Optional parameter. Do not wait for the long-running operation to finish.  ### 
        'no-wait': "{{ item['no-wait'] | default('') }}" 
 - debug: msg="{{ az_network_application_gateway_http_settings_delete }}"          
 - name: "az network application-gateway http-settings delete: Delete HTTP settings." 
   command: |                                      
     az network application-gateway http-settings delete                            
                 --gateway-name {{ az_network_application_gateway_http_settings_delete.input['gateway-name'] }} 
                 --name {{ az_network_application_gateway_http_settings_delete.input['name'] }} 
                 --resource-group {{ az_network_application_gateway_http_settings_delete.input['resource-group'] }} 
                 {%if az_network_application_gateway_http_settings_delete.input['no-wait'] %} --no-wait az_network_application_gateway_http_settings_delete.input['no-wait'] {%endif %} 
   register: output  
 - set_fact: 
    az_network_application_gateway_http_settings_delete: "{{ az_network_application_gateway_http_settings_delete|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_network_application_gateway_http_settings_delete }}" 
