

 - name: Set input params for az_network_application_gateway_waf_config_show
   set_fact: 
     az_network_application_gateway_waf_config_show:
       input: 
         ###  Required parameter. The name of the application gateway.  ### 
        'gateway-name': "{{ item['gateway-name'] | default('') }}" 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
 - debug: msg="{{ az_network_application_gateway_waf_config_show }}"          
 - name: "az network application-gateway waf-config show: Get the firewall configuration of a web application." 
   command: |                                      
     az network application-gateway waf-config show                            
                 --gateway-name {{ az_network_application_gateway_waf_config_show.input['gateway-name'] }} 
                 --resource-group {{ az_network_application_gateway_waf_config_show.input['resource-group'] }} 
   register: output  
 - set_fact: 
    az_network_application_gateway_waf_config_show: "{{ az_network_application_gateway_waf_config_show|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_network_application_gateway_waf_config_show }}" 
