

 - name: Set input params for az_network_application_gateway_ssl_cert_create
   set_fact: 
     az_network_application_gateway_ssl_cert_create:
       input: 
         ###  Required parameter. The path to the PFX certificate file.  ### 
        'cert-file': "{{ item['cert-file'] | default('') }}" 
         ###  Required parameter. Certificate password.  ### 
        'cert-password': "{{ item['cert-password'] | default('') }}" 
         ###  Required parameter. The name of the application gateway.  ### 
        'gateway-name': "{{ item['gateway-name'] | default('') }}" 
         ###  Required parameter. The name of the SSL certificate.  ### 
        'name': "{{ item['name'] | default('') }}" 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
         ###  Optional parameter. Do not wait for the long-running operation to finish.  ### 
        'no-wait': "{{ item['no-wait'] | default('') }}" 
 - debug: msg="{{ az_network_application_gateway_ssl_cert_create }}"          
 - name: "az network application-gateway ssl-cert create: Upload an SSL certificate." 
   command: |                                      
     az network application-gateway ssl-cert create                            
                 --cert-file {{ az_network_application_gateway_ssl_cert_create.input['cert-file'] }} 
                 --cert-password {{ az_network_application_gateway_ssl_cert_create.input['cert-password'] }} 
                 --gateway-name {{ az_network_application_gateway_ssl_cert_create.input['gateway-name'] }} 
                 --name {{ az_network_application_gateway_ssl_cert_create.input['name'] }} 
                 --resource-group {{ az_network_application_gateway_ssl_cert_create.input['resource-group'] }} 
                 {%if az_network_application_gateway_ssl_cert_create.input['no-wait'] %} --no-wait az_network_application_gateway_ssl_cert_create.input['no-wait'] {%endif %} 
   register: output  
 - set_fact: 
    az_network_application_gateway_ssl_cert_create: "{{ az_network_application_gateway_ssl_cert_create|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_network_application_gateway_ssl_cert_create }}" 
