

 - name: Set input params for az_network_application_gateway_waf_config_set
   set_fact: 
     az_network_application_gateway_waf_config_set:
       input: 
         ###  Required parameter. Specify whether the application firewall is enabled.  ### 
        'enabled': "{{ item['enabled'] | default('') }}" 
         ###  Required parameter. The name of the application gateway.  ### 
        'gateway-name': "{{ item['gateway-name'] | default('') }}" 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
         ###  Optional parameter. Space separated list of rule groups to disable. To disable individual rules, use `--disabled-rules`.  ### 
        'disabled-rule-groups': "{{ item['disabled-rule-groups'] | default('') }}" 
         ###  Optional parameter. Space separated list of rule IDs to disable.  ### 
        'disabled-rules': "{{ item['disabled-rules'] | default('') }}" 
         ###  Optional parameter. Web application firewall mode.  ### 
        'firewall-mode': "{{ item['firewall-mode'] | default('') }}" 
         ###  Optional parameter. Do not wait for the long-running operation to finish.  ### 
        'no-wait': "{{ item['no-wait'] | default('') }}" 
         ###  Optional parameter. Rule set type.  ### 
        'rule-set-type': "{{ item['rule-set-type'] | default('') }}" 
         ###  Optional parameter. Rule set version.  ### 
        'rule-set-version': "{{ item['rule-set-version'] | default('') }}" 
 - debug: msg="{{ az_network_application_gateway_waf_config_set }}"          
 - name: "az network application-gateway waf-config set: Update the firewall configuration of a web application." 
   command: |                                      
     az network application-gateway waf-config set                            
                 --enabled {{ az_network_application_gateway_waf_config_set.input['enabled'] }} 
                 --gateway-name {{ az_network_application_gateway_waf_config_set.input['gateway-name'] }} 
                 --resource-group {{ az_network_application_gateway_waf_config_set.input['resource-group'] }} 
                 {%if az_network_application_gateway_waf_config_set.input['disabled-rule-groups'] %} --disabled-rule-groups az_network_application_gateway_waf_config_set.input['disabled-rule-groups'] {%endif %} 
                 {%if az_network_application_gateway_waf_config_set.input['disabled-rules'] %} --disabled-rules az_network_application_gateway_waf_config_set.input['disabled-rules'] {%endif %} 
                 {%if az_network_application_gateway_waf_config_set.input['firewall-mode'] %} --firewall-mode az_network_application_gateway_waf_config_set.input['firewall-mode'] {%endif %} 
                 {%if az_network_application_gateway_waf_config_set.input['no-wait'] %} --no-wait az_network_application_gateway_waf_config_set.input['no-wait'] {%endif %} 
                 {%if az_network_application_gateway_waf_config_set.input['rule-set-type'] %} --rule-set-type az_network_application_gateway_waf_config_set.input['rule-set-type'] {%endif %} 
                 {%if az_network_application_gateway_waf_config_set.input['rule-set-version'] %} --rule-set-version az_network_application_gateway_waf_config_set.input['rule-set-version'] {%endif %} 
   register: output  
 - set_fact: 
    az_network_application_gateway_waf_config_set: "{{ az_network_application_gateway_waf_config_set|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_network_application_gateway_waf_config_set }}" 
