

 - name: Set input params for az_network_vnet_gateway_list_advertised_routes
   set_fact: 
     az_network_vnet_gateway_list_advertised_routes:
       input: 
         ###  Required parameter. Name of the VNet gateway.  ### 
        'name': "{{ item['name'] | default('') }}" 
         ###  Required parameter. The IP address of the peer.  ### 
        'peer': "{{ item['peer'] | default('') }}" 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
 - debug: msg="{{ az_network_vnet_gateway_list_advertised_routes }}"          
 - name: "az network vnet-gateway list-advertised-routes: This operation retrieves a list of routes the virtual network gateway is advertising to the specified peer." 
   command: |                                      
     az network vnet-gateway list-advertised-routes                            
                 --name {{ az_network_vnet_gateway_list_advertised_routes.input['name'] }} 
                 --peer {{ az_network_vnet_gateway_list_advertised_routes.input['peer'] }} 
                 --resource-group {{ az_network_vnet_gateway_list_advertised_routes.input['resource-group'] }} 
   register: output  
 - set_fact: 
    az_network_vnet_gateway_list_advertised_routes: "{{ az_network_vnet_gateway_list_advertised_routes|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_network_vnet_gateway_list_advertised_routes }}" 
