

 - name: Set input params for az_network_application_gateway_redirect_config_create
   set_fact: 
     az_network_application_gateway_redirect_config_create:
       input: 
         ###  Required parameter. The name of the application gateway.  ### 
        'gateway-name': "{{ item['gateway-name'] | default('') }}" 
         ###  Required parameter. The name of the redirect configuration.  ### 
        'name': "{{ item['name'] | default('') }}" 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
         ###  Required parameter. HTTP redirection type.  ### 
        'type': "{{ item['type'] | default('') }}" 
         ###  Optional parameter. Include path in the redirected url.  ### 
        'include-path': "{{ item['include-path'] | default('') }}" 
         ###  Optional parameter. Include query string in the redirected url.  ### 
        'include-query-string': "{{ item['include-query-string'] | default('') }}" 
         ###  Optional parameter. Do not wait for the long-running operation to finish.  ### 
        'no-wait': "{{ item['no-wait'] | default('') }}" 
         ###  Optional parameter. Name or ID of the HTTP listener to redirect the request to.  ### 
        'target-listener': "{{ item['target-listener'] | default('') }}" 
         ###  Optional parameter. URL to redirect the request to.  ### 
        'target-url': "{{ item['target-url'] | default('') }}" 
 - debug: msg="{{ az_network_application_gateway_redirect_config_create }}"          
 - name: "az network application-gateway redirect-config create: Create a redirect configuration." 
   command: |                                      
     az network application-gateway redirect-config create                            
                 --gateway-name {{ az_network_application_gateway_redirect_config_create.input['gateway-name'] }} 
                 --name {{ az_network_application_gateway_redirect_config_create.input['name'] }} 
                 --resource-group {{ az_network_application_gateway_redirect_config_create.input['resource-group'] }} 
                 --type {{ az_network_application_gateway_redirect_config_create.input['type'] }} 
                 {%if az_network_application_gateway_redirect_config_create.input['include-path'] %} --include-path az_network_application_gateway_redirect_config_create.input['include-path'] {%endif %} 
                 {%if az_network_application_gateway_redirect_config_create.input['include-query-string'] %} --include-query-string az_network_application_gateway_redirect_config_create.input['include-query-string'] {%endif %} 
                 {%if az_network_application_gateway_redirect_config_create.input['no-wait'] %} --no-wait az_network_application_gateway_redirect_config_create.input['no-wait'] {%endif %} 
                 {%if az_network_application_gateway_redirect_config_create.input['target-listener'] %} --target-listener az_network_application_gateway_redirect_config_create.input['target-listener'] {%endif %} 
                 {%if az_network_application_gateway_redirect_config_create.input['target-url'] %} --target-url az_network_application_gateway_redirect_config_create.input['target-url'] {%endif %} 
   register: output  
 - set_fact: 
    az_network_application_gateway_redirect_config_create: "{{ az_network_application_gateway_redirect_config_create|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_network_application_gateway_redirect_config_create }}" 
