

 - name: Set input params for az_network_application_gateway_update
   set_fact: 
     az_network_application_gateway_update:
       input: 
         ###  Required parameter. The name of the application gateway.  ### 
        'name': "{{ item['name'] | default('') }}" 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
         ###  Optional parameter. The number of instances to use with the application gateway.  ### 
        'capacity': "{{ item['capacity'] | default('') }}" 
         ###  Optional parameter. Use HTTP2 for the application gateway.  ### 
        'http2': "{{ item['http2'] | default('') }}" 
         ###  Optional parameter. Do not wait for the long-running operation to finish.  ### 
        'no-wait': "{{ item['no-wait'] | default('') }}" 
         ###  Optional parameter. The name of the SKU.  ### 
        'sku': "{{ item['sku'] | default('') }}" 
         ###  Optional parameter. Space separated tags in 'key[=value]' format. Use "" to clear existing tags.  ### 
        'rtags': "{{ item['rtags'] | default('') }}" 
         ###  Optional parameter. Add an object to a list of objects by specifying a path and key value pairs.  Example: --add property.listProperty <key=value, string or JSON string>.  ### 
        'add': "{{ item['add'] | default('') }}" 
         ###  Optional parameter. Remove a property or an element from a list.  Example: --remove property.list <indexToRemove> OR --remove propertyToRemove.  ### 
        'remove': "{{ item['remove'] | default('') }}" 
         ###  Optional parameter. Update an object by specifying a property path and value to set.  Example: --set property1.property2=<value>.  ### 
        'set': "{{ item['set'] | default('') }}" 
 - debug: msg="{{ az_network_application_gateway_update }}"          
 - name: "az network application-gateway update: Update an application gateway." 
   command: |                                      
     az network application-gateway update                            
                 --name {{ az_network_application_gateway_update.input['name'] }} 
                 --resource-group {{ az_network_application_gateway_update.input['resource-group'] }} 
                 {%if az_network_application_gateway_update.input['capacity'] %} --capacity az_network_application_gateway_update.input['capacity'] {%endif %} 
                 {%if az_network_application_gateway_update.input['http2'] %} --http2 az_network_application_gateway_update.input['http2'] {%endif %} 
                 {%if az_network_application_gateway_update.input['no-wait'] %} --no-wait az_network_application_gateway_update.input['no-wait'] {%endif %} 
                 {%if az_network_application_gateway_update.input['sku'] %} --sku az_network_application_gateway_update.input['sku'] {%endif %} 
                 {%if az_network_application_gateway_update.input['rtags'] %} --tags az_network_application_gateway_update.input['rtags'] {%endif %} 
                 {%if az_network_application_gateway_update.input['add'] %} --add az_network_application_gateway_update.input['add'] {%endif %} 
                 {%if az_network_application_gateway_update.input['remove'] %} --remove az_network_application_gateway_update.input['remove'] {%endif %} 
                 {%if az_network_application_gateway_update.input['set'] %} --set az_network_application_gateway_update.input['set'] {%endif %} 
   register: output  
 - set_fact: 
    az_network_application_gateway_update: "{{ az_network_application_gateway_update|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_network_application_gateway_update }}" 
