

 - name: Set input params for az_network_application_gateway_start
   set_fact: 
     az_network_application_gateway_start:
       input: 
         ###  Required parameter. The name of the application gateway.  ### 
        'name': "{{ item['name'] | default('') }}" 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
 - debug: msg="{{ az_network_application_gateway_start }}"          
 - name: "az network application-gateway start: Start an application gateway." 
   command: |                                      
     az network application-gateway start                            
                 --name {{ az_network_application_gateway_start.input['name'] }} 
                 --resource-group {{ az_network_application_gateway_start.input['resource-group'] }} 
   register: output  
 - set_fact: 
    az_network_application_gateway_start: "{{ az_network_application_gateway_start|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_network_application_gateway_start }}" 
