

 - name: Set input params for az_network_application_gateway_address_pool_update
   set_fact: 
     az_network_application_gateway_address_pool_update:
       input: 
         ###  Required parameter. The name of the application gateway.  ### 
        'gateway-name': "{{ item['gateway-name'] | default('') }}" 
         ###  Required parameter. The name of the backend address pool.  ### 
        'name': "{{ item['name'] | default('') }}" 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
         ###  Optional parameter. Do not wait for the long-running operation to finish.  ### 
        'no-wait': "{{ item['no-wait'] | default('') }}" 
         ###  Optional parameter. Space separated list of IP addresses or DNS names corresponding to backend servers.  ### 
        'servers': "{{ item['servers'] | default('') }}" 
         ###  Optional parameter. Add an object to a list of objects by specifying a path and key value pairs.  Example: --add property.listProperty <key=value, string or JSON string>.  ### 
        'add': "{{ item['add'] | default('') }}" 
         ###  Optional parameter. Remove a property or an element from a list.  Example: --remove property.list <indexToRemove> OR --remove propertyToRemove.  ### 
        'remove': "{{ item['remove'] | default('') }}" 
         ###  Optional parameter. Update an object by specifying a property path and value to set.  Example: --set property1.property2=<value>.  ### 
        'set': "{{ item['set'] | default('') }}" 
 - debug: msg="{{ az_network_application_gateway_address_pool_update }}"          
 - name: "az network application-gateway address-pool update: Update a backend address pool." 
   command: |                                      
     az network application-gateway address-pool update                            
                 --gateway-name {{ az_network_application_gateway_address_pool_update.input['gateway-name'] }} 
                 --name {{ az_network_application_gateway_address_pool_update.input['name'] }} 
                 --resource-group {{ az_network_application_gateway_address_pool_update.input['resource-group'] }} 
                 {%if az_network_application_gateway_address_pool_update.input['no-wait'] %} --no-wait az_network_application_gateway_address_pool_update.input['no-wait'] {%endif %} 
                 {%if az_network_application_gateway_address_pool_update.input['servers'] %} --servers az_network_application_gateway_address_pool_update.input['servers'] {%endif %} 
                 {%if az_network_application_gateway_address_pool_update.input['add'] %} --add az_network_application_gateway_address_pool_update.input['add'] {%endif %} 
                 {%if az_network_application_gateway_address_pool_update.input['remove'] %} --remove az_network_application_gateway_address_pool_update.input['remove'] {%endif %} 
                 {%if az_network_application_gateway_address_pool_update.input['set'] %} --set az_network_application_gateway_address_pool_update.input['set'] {%endif %} 
   register: output  
 - set_fact: 
    az_network_application_gateway_address_pool_update: "{{ az_network_application_gateway_address_pool_update|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_network_application_gateway_address_pool_update }}" 
