

 - name: Set input params for az_network_application_gateway_redirect_config_update
   set_fact: 
     az_network_application_gateway_redirect_config_update:
       input: 
         ###  Required parameter. The name of the application gateway.  ### 
        'gateway-name': "{{ item['gateway-name'] | default('') }}" 
         ###  Required parameter. The name of the redirect configuration.  ### 
        'name': "{{ item['name'] | default('') }}" 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
         ###  Optional parameter. Include path in the redirected url.  ### 
        'include-path': "{{ item['include-path'] | default('') }}" 
         ###  Optional parameter. Include query string in the redirected url.  ### 
        'include-query-string': "{{ item['include-query-string'] | default('') }}" 
         ###  Optional parameter. Do not wait for the long-running operation to finish.  ### 
        'no-wait': "{{ item['no-wait'] | default('') }}" 
         ###  Optional parameter. Name or ID of the HTTP listener to redirect the request to.  ### 
        'target-listener': "{{ item['target-listener'] | default('') }}" 
         ###  Optional parameter. URL to redirect the request to.  ### 
        'target-url': "{{ item['target-url'] | default('') }}" 
         ###  Optional parameter. HTTP redirection type.  ### 
        'type': "{{ item['type'] | default('') }}" 
         ###  Optional parameter. Add an object to a list of objects by specifying a path and key value pairs.  Example: --add property.listProperty <key=value, string or JSON string>.  ### 
        'add': "{{ item['add'] | default('') }}" 
         ###  Optional parameter. Remove a property or an element from a list.  Example: --remove property.list <indexToRemove> OR --remove propertyToRemove.  ### 
        'remove': "{{ item['remove'] | default('') }}" 
         ###  Optional parameter. Update an object by specifying a property path and value to set.  Example: --set property1.property2=<value>.  ### 
        'set': "{{ item['set'] | default('') }}" 
 - debug: msg="{{ az_network_application_gateway_redirect_config_update }}"          
 - name: "az network application-gateway redirect-config update: Update a redirect configuration." 
   command: |                                      
     az network application-gateway redirect-config update                            
                 --gateway-name {{ az_network_application_gateway_redirect_config_update.input['gateway-name'] }} 
                 --name {{ az_network_application_gateway_redirect_config_update.input['name'] }} 
                 --resource-group {{ az_network_application_gateway_redirect_config_update.input['resource-group'] }} 
                 {%if az_network_application_gateway_redirect_config_update.input['include-path'] %} --include-path az_network_application_gateway_redirect_config_update.input['include-path'] {%endif %} 
                 {%if az_network_application_gateway_redirect_config_update.input['include-query-string'] %} --include-query-string az_network_application_gateway_redirect_config_update.input['include-query-string'] {%endif %} 
                 {%if az_network_application_gateway_redirect_config_update.input['no-wait'] %} --no-wait az_network_application_gateway_redirect_config_update.input['no-wait'] {%endif %} 
                 {%if az_network_application_gateway_redirect_config_update.input['target-listener'] %} --target-listener az_network_application_gateway_redirect_config_update.input['target-listener'] {%endif %} 
                 {%if az_network_application_gateway_redirect_config_update.input['target-url'] %} --target-url az_network_application_gateway_redirect_config_update.input['target-url'] {%endif %} 
                 {%if az_network_application_gateway_redirect_config_update.input['type'] %} --type az_network_application_gateway_redirect_config_update.input['type'] {%endif %} 
                 {%if az_network_application_gateway_redirect_config_update.input['add'] %} --add az_network_application_gateway_redirect_config_update.input['add'] {%endif %} 
                 {%if az_network_application_gateway_redirect_config_update.input['remove'] %} --remove az_network_application_gateway_redirect_config_update.input['remove'] {%endif %} 
                 {%if az_network_application_gateway_redirect_config_update.input['set'] %} --set az_network_application_gateway_redirect_config_update.input['set'] {%endif %} 
   register: output  
 - set_fact: 
    az_network_application_gateway_redirect_config_update: "{{ az_network_application_gateway_redirect_config_update|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_network_application_gateway_redirect_config_update }}" 
