

 - name: Set input params for az_redis_update_settings
   set_fact: 
     az_redis_update_settings:
       input: 
         ###  Required parameter. Name of the redis cache.  ### 
        'name': "{{ item['name'] | default('') }}" 
         ###  Required parameter.   ### 
        'redis-configuration': "{{ item['redis-configuration'] | default('') }}" 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
 - debug: msg="{{ az_redis_update_settings }}"          
 - name: "az redis update-settings: (DEPRECATED) Update the settings of a Redis cache." 
   command: |                                      
     az redis update-settings                            
                 --name {{ az_redis_update_settings.input['name'] }} 
                 --redis-configuration {{ az_redis_update_settings.input['redis-configuration'] }} 
                 --resource-group {{ az_redis_update_settings.input['resource-group'] }} 
   register: output  
 - set_fact: 
    az_redis_update_settings: "{{ az_redis_update_settings|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_redis_update_settings }}" 
