

 - name: Set input params for az_vm_diagnostics_get_default_config
   set_fact: 
     az_vm_diagnostics_get_default_config:
       input: 
         ###  Optional parameter.   ### 
        'is-windows-os': "{{ item['is-windows-os'] | default('') }}" 
 - debug: msg="{{ az_vm_diagnostics_get_default_config }}"          
 - name: "az vm diagnostics get-default-config: Get the default configuration settings for a VM." 
   command: |                                      
     az vm diagnostics get-default-config                            
                 {%if az_vm_diagnostics_get_default_config.input['is-windows-os'] %} --is-windows-os az_vm_diagnostics_get_default_config.input['is-windows-os'] {%endif %} 
   register: output  
 - set_fact: 
    az_vm_diagnostics_get_default_config: "{{ az_vm_diagnostics_get_default_config|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_vm_diagnostics_get_default_config }}" 
