

 - name: Set input params for az_webapp_deployment_slot_swap
   set_fact: 
     az_webapp_deployment_slot_swap:
       input: 
         ###  Required parameter. Name of the webapp.  ### 
        'name': "{{ item['name'] | default('') }}" 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
         ###  Required parameter. The name of the slot.  ### 
        'slot': "{{ item['slot'] | default('') }}" 
         ###  Optional parameter. Swap types. use 'preview' to apply target slot's settings on the source slot first; use 'swap' to complete it; use 'reset' to reset the swap.  ### 
        'action': "{{ item['action'] | default('') }}" 
         ###  Optional parameter. Target slot to swap, default to 'production'.  ### 
        'target-slot': "{{ item['target-slot'] | default('') }}" 
 - debug: msg="{{ az_webapp_deployment_slot_swap }}"          
 - name: "az webapp deployment slot swap: Change deployment slots for a web app." 
   command: |                                      
     az webapp deployment slot swap                            
                 --name {{ az_webapp_deployment_slot_swap.input['name'] }} 
                 --resource-group {{ az_webapp_deployment_slot_swap.input['resource-group'] }} 
                 --slot {{ az_webapp_deployment_slot_swap.input['slot'] }} 
                 {%if az_webapp_deployment_slot_swap.input['action'] %} --action az_webapp_deployment_slot_swap.input['action'] {%endif %} 
                 {%if az_webapp_deployment_slot_swap.input['target-slot'] %} --target-slot az_webapp_deployment_slot_swap.input['target-slot'] {%endif %} 
   register: output  
 - set_fact: 
    az_webapp_deployment_slot_swap: "{{ az_webapp_deployment_slot_swap|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_webapp_deployment_slot_swap }}" 
