

 - name: Set input params for az_webapp_deployment_source_config_zip
   set_fact: 
     az_webapp_deployment_source_config_zip:
       input: 
         ###  Required parameter. Name of the web. You can configure the default using 'az configure --defaults web=<name>'.  ### 
        'name': "{{ item['name'] | default('') }}" 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
         ###  Required parameter.   ### 
        'src': "{{ item['src'] | default('') }}" 
         ###  Optional parameter. The name of the slot. Default to the productions slot if not specified.  ### 
        'slot': "{{ item['slot'] | default('') }}" 
 - debug: msg="{{ az_webapp_deployment_source_config_zip }}"          
 - name: "az webapp deployment source config-zip: Perform deployment using the kudu zip push deployment for a webapp." 
   command: |                                      
     az webapp deployment source config-zip                            
                 --name {{ az_webapp_deployment_source_config_zip.input['name'] }} 
                 --resource-group {{ az_webapp_deployment_source_config_zip.input['resource-group'] }} 
                 --src {{ az_webapp_deployment_source_config_zip.input['src'] }} 
                 {%if az_webapp_deployment_source_config_zip.input['slot'] %} --slot az_webapp_deployment_source_config_zip.input['slot'] {%endif %} 
   register: output  
 - set_fact: 
    az_webapp_deployment_source_config_zip: "{{ az_webapp_deployment_source_config_zip|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_webapp_deployment_source_config_zip }}" 
