

 - name: Set input params for az_webapp_deployment_list_publishing_profiles
   set_fact: 
     az_webapp_deployment_list_publishing_profiles:
       input: 
         ###  Required parameter. Name of the web. You can configure the default using 'az configure --defaults web=<name>'.  ### 
        'name': "{{ item['name'] | default('') }}" 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
         ###  Optional parameter. The name of the slot. Default to the productions slot if not specified.  ### 
        'slot': "{{ item['slot'] | default('') }}" 
 - debug: msg="{{ az_webapp_deployment_list_publishing_profiles }}"          
 - name: "az webapp deployment list-publishing-profiles: Get the details for available web app deployment profiles." 
   command: |                                      
     az webapp deployment list-publishing-profiles                            
                 --name {{ az_webapp_deployment_list_publishing_profiles.input['name'] }} 
                 --resource-group {{ az_webapp_deployment_list_publishing_profiles.input['resource-group'] }} 
                 {%if az_webapp_deployment_list_publishing_profiles.input['slot'] %} --slot az_webapp_deployment_list_publishing_profiles.input['slot'] {%endif %} 
   register: output  
 - set_fact: 
    az_webapp_deployment_list_publishing_profiles: "{{ az_webapp_deployment_list_publishing_profiles|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_webapp_deployment_list_publishing_profiles }}" 
