

 - name: Set input params for az_webapp_deployment_source_update_token
   set_fact: 
     az_webapp_deployment_source_update_token:
       input: 
         ###  Optional parameter. Git access token required for auto sync.  ### 
        'git-token': "{{ item['git-token'] | default('') }}" 
 - debug: msg="{{ az_webapp_deployment_source_update_token }}"          
 - name: "az webapp deployment source update-token: Update source control token cached in Azure app service." 
   command: |                                      
     az webapp deployment source update-token                            
                 {%if az_webapp_deployment_source_update_token.input['git-token'] %} --git-token az_webapp_deployment_source_update_token.input['git-token'] {%endif %} 
   register: output  
 - set_fact: 
    az_webapp_deployment_source_update_token: "{{ az_webapp_deployment_source_update_token|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_webapp_deployment_source_update_token }}" 
