

 - name: Set input params for az_webapp_deployment_slot_auto_swap
   set_fact: 
     az_webapp_deployment_slot_auto_swap:
       input: 
         ###  Required parameter. Name of the webapp.  ### 
        'name': "{{ item['name'] | default('') }}" 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
         ###  Required parameter. The name of the slot.  ### 
        'slot': "{{ item['slot'] | default('') }}" 
         ###  Optional parameter. Target slot to auto swap.  ### 
        'auto-swap-slot': "{{ item['auto-swap-slot'] | default('') }}" 
         ###  Optional parameter. Disable auto swap.  ### 
        'disable': "{{ item['disable'] | default('') }}" 
 - debug: msg="{{ az_webapp_deployment_slot_auto_swap }}"          
 - name: "az webapp deployment slot auto-swap: Configure deployment slot auto swap." 
   command: |                                      
     az webapp deployment slot auto-swap                            
                 --name {{ az_webapp_deployment_slot_auto_swap.input['name'] }} 
                 --resource-group {{ az_webapp_deployment_slot_auto_swap.input['resource-group'] }} 
                 --slot {{ az_webapp_deployment_slot_auto_swap.input['slot'] }} 
                 {%if az_webapp_deployment_slot_auto_swap.input['auto-swap-slot'] %} --auto-swap-slot az_webapp_deployment_slot_auto_swap.input['auto-swap-slot'] {%endif %} 
                 {%if az_webapp_deployment_slot_auto_swap.input['disable'] %} --disable az_webapp_deployment_slot_auto_swap.input['disable'] {%endif %} 
   register: output  
 - set_fact: 
    az_webapp_deployment_slot_auto_swap: "{{ az_webapp_deployment_slot_auto_swap|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_webapp_deployment_slot_auto_swap }}" 
