

 - name: Set input params for az_webapp_config_backup_create
   set_fact: 
     az_webapp_config_backup_create:
       input: 
         ###  Required parameter. URL with SAS token to the blob storage container.  ### 
        'container-url': "{{ item['container-url'] | default('') }}" 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
         ###  Required parameter. The name of the webapp.  ### 
        'webapp-name': "{{ item['webapp-name'] | default('') }}" 
         ###  Optional parameter. Name of the backup. If unspecified, the backup will be named with the webapp name and a timestamp.  ### 
        'backup-name': "{{ item['backup-name'] | default('') }}" 
         ###  Optional parameter. The name of the slot. Default to the productions slot if not specified.  ### 
        'slot': "{{ item['slot'] | default('') }}" 
         ###  Optional parameter. Connection string for the database in the backup.  ### 
        'db-connection-string': "{{ item['db-connection-string'] | default('') }}" 
         ###  Optional parameter. Name of the database in the backup.  ### 
        'db-name': "{{ item['db-name'] | default('') }}" 
         ###  Optional parameter. Type of database in the backup.  ### 
        'db-type': "{{ item['db-type'] | default('') }}" 
 - debug: msg="{{ az_webapp_config_backup_create }}"          
 - name: "az webapp config backup create: Create a backup of a web app." 
   command: |                                      
     az webapp config backup create                            
                 --container-url {{ az_webapp_config_backup_create.input['container-url'] }} 
                 --resource-group {{ az_webapp_config_backup_create.input['resource-group'] }} 
                 --webapp-name {{ az_webapp_config_backup_create.input['webapp-name'] }} 
                 {%if az_webapp_config_backup_create.input['backup-name'] %} --backup-name az_webapp_config_backup_create.input['backup-name'] {%endif %} 
                 {%if az_webapp_config_backup_create.input['slot'] %} --slot az_webapp_config_backup_create.input['slot'] {%endif %} 
                 {%if az_webapp_config_backup_create.input['db-connection-string'] %} --db-connection-string az_webapp_config_backup_create.input['db-connection-string'] {%endif %} 
                 {%if az_webapp_config_backup_create.input['db-name'] %} --db-name az_webapp_config_backup_create.input['db-name'] {%endif %} 
                 {%if az_webapp_config_backup_create.input['db-type'] %} --db-type az_webapp_config_backup_create.input['db-type'] {%endif %} 
   register: output  
 - set_fact: 
    az_webapp_config_backup_create: "{{ az_webapp_config_backup_create|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_webapp_config_backup_create }}" 
