

 - name: Set input params for az_webapp_config_appsettings_delete
   set_fact: 
     az_webapp_config_appsettings_delete:
       input: 
         ###  Required parameter. Name of the web. You can configure the default using 'az configure --defaults web=<name>'.  ### 
        'name': "{{ item['name'] | default('') }}" 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
         ###  Required parameter. Space separated appsettings names.  ### 
        'setting-names': "{{ item['setting-names'] | default('') }}" 
         ###  Optional parameter. The name of the slot. Default to the productions slot if not specified.  ### 
        'slot': "{{ item['slot'] | default('') }}" 
 - debug: msg="{{ az_webapp_config_appsettings_delete }}"          
 - name: "az webapp config appsettings delete: Delete web app settings." 
   command: |                                      
     az webapp config appsettings delete                            
                 --name {{ az_webapp_config_appsettings_delete.input['name'] }} 
                 --resource-group {{ az_webapp_config_appsettings_delete.input['resource-group'] }} 
                 --setting-names {{ az_webapp_config_appsettings_delete.input['setting-names'] }} 
                 {%if az_webapp_config_appsettings_delete.input['slot'] %} --slot az_webapp_config_appsettings_delete.input['slot'] {%endif %} 
   register: output  
 - set_fact: 
    az_webapp_config_appsettings_delete: "{{ az_webapp_config_appsettings_delete|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_webapp_config_appsettings_delete }}" 
