

 - name: Set input params for az_webapp_config_hostname_delete
   set_fact: 
     az_webapp_config_hostname_delete:
       input: 
         ###  Required parameter. Hostname assigned to the site, such as custom domains.  ### 
        'hostname': "{{ item['hostname'] | default('') }}" 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
         ###  Required parameter. Webapp name. You can configure the default using 'az configure --defaults web=<name>'.  ### 
        'webapp-name': "{{ item['webapp-name'] | default('') }}" 
         ###  Optional parameter. The name of the slot. Default to the productions slot if not specified.  ### 
        'slot': "{{ item['slot'] | default('') }}" 
 - debug: msg="{{ az_webapp_config_hostname_delete }}"          
 - name: "az webapp config hostname delete: Unbind a hostname from a web app." 
   command: |                                      
     az webapp config hostname delete                            
                 --hostname {{ az_webapp_config_hostname_delete.input['hostname'] }} 
                 --resource-group {{ az_webapp_config_hostname_delete.input['resource-group'] }} 
                 --webapp-name {{ az_webapp_config_hostname_delete.input['webapp-name'] }} 
                 {%if az_webapp_config_hostname_delete.input['slot'] %} --slot az_webapp_config_hostname_delete.input['slot'] {%endif %} 
   register: output  
 - set_fact: 
    az_webapp_config_hostname_delete: "{{ az_webapp_config_hostname_delete|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_webapp_config_hostname_delete }}" 
