

 - name: Set input params for az_webapp_deployment_source_config_local_git
   set_fact: 
     az_webapp_deployment_source_config_local_git:
       input: 
         ###  Required parameter. Name of the web. You can configure the default using 'az configure --defaults web=<name>'.  ### 
        'name': "{{ item['name'] | default('') }}" 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
         ###  Optional parameter. The name of the slot. Default to the productions slot if not specified.  ### 
        'slot': "{{ item['slot'] | default('') }}" 
 - debug: msg="{{ az_webapp_deployment_source_config_local_git }}"          
 - name: "az webapp deployment source config-local-git: Get a URL for a git repository endpoint to clone and push to for web app deployment." 
   command: |                                      
     az webapp deployment source config-local-git                            
                 --name {{ az_webapp_deployment_source_config_local_git.input['name'] }} 
                 --resource-group {{ az_webapp_deployment_source_config_local_git.input['resource-group'] }} 
                 {%if az_webapp_deployment_source_config_local_git.input['slot'] %} --slot az_webapp_deployment_source_config_local_git.input['slot'] {%endif %} 
   register: output  
 - set_fact: 
    az_webapp_deployment_source_config_local_git: "{{ az_webapp_deployment_source_config_local_git|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_webapp_deployment_source_config_local_git }}" 
