

 - name: Set input params for az_webapp_deployment_slot_list
   set_fact: 
     az_webapp_deployment_slot_list:
       input: 
         ###  Required parameter. Name of the webapp.  ### 
        'name': "{{ item['name'] | default('') }}" 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
 - debug: msg="{{ az_webapp_deployment_slot_list }}"          
 - name: "az webapp deployment slot list: List all deployment slots." 
   command: |                                      
     az webapp deployment slot list                            
                 --name {{ az_webapp_deployment_slot_list.input['name'] }} 
                 --resource-group {{ az_webapp_deployment_slot_list.input['resource-group'] }} 
   register: output  
 - set_fact: 
    az_webapp_deployment_slot_list: "{{ az_webapp_deployment_slot_list|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_webapp_deployment_slot_list }}" 
