

 - name: Set input params for az_webapp_config_backup_show
   set_fact: 
     az_webapp_config_backup_show:
       input: 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
         ###  Required parameter. The name of the webapp.  ### 
        'webapp-name': "{{ item['webapp-name'] | default('') }}" 
         ###  Optional parameter. The name of the slot. Default to the productions slot if not specified.  ### 
        'slot': "{{ item['slot'] | default('') }}" 
 - debug: msg="{{ az_webapp_config_backup_show }}"          
 - name: "az webapp config backup show: Show the backup schedule for a web app." 
   command: |                                      
     az webapp config backup show                            
                 --resource-group {{ az_webapp_config_backup_show.input['resource-group'] }} 
                 --webapp-name {{ az_webapp_config_backup_show.input['webapp-name'] }} 
                 {%if az_webapp_config_backup_show.input['slot'] %} --slot az_webapp_config_backup_show.input['slot'] {%endif %} 
   register: output  
 - set_fact: 
    az_webapp_config_backup_show: "{{ az_webapp_config_backup_show|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_webapp_config_backup_show }}" 
