

 - name: Set input params for az_webapp_deployment_user_show
   set_fact: 
     az_webapp_deployment_user_show:
       input: 
 - debug: msg="{{ az_webapp_deployment_user_show }}"          
 - name: "az webapp deployment user show: Gets publishing user." 
   command: |                                      
     az webapp deployment user show                            
   register: output  
 - set_fact: 
    az_webapp_deployment_user_show: "{{ az_webapp_deployment_user_show|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_webapp_deployment_user_show }}" 
