

 - name: Set input params for az_webapp_config_hostname_get_external_ip
   set_fact: 
     az_webapp_config_hostname_get_external_ip:
       input: 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
         ###  Required parameter. Webapp name. You can configure the default using 'az configure --defaults web=<name>'.  ### 
        'webapp-name': "{{ item['webapp-name'] | default('') }}" 
 - debug: msg="{{ az_webapp_config_hostname_get_external_ip }}"          
 - name: "az webapp config hostname get-external-ip: Get the external-facing IP address for a web app." 
   command: |                                      
     az webapp config hostname get-external-ip                            
                 --resource-group {{ az_webapp_config_hostname_get_external_ip.input['resource-group'] }} 
                 --webapp-name {{ az_webapp_config_hostname_get_external_ip.input['webapp-name'] }} 
   register: output  
 - set_fact: 
    az_webapp_config_hostname_get_external_ip: "{{ az_webapp_config_hostname_get_external_ip|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_webapp_config_hostname_get_external_ip }}" 
