

 - name: Set input params for az_webapp_deployment_slot_create
   set_fact: 
     az_webapp_deployment_slot_create:
       input: 
         ###  Required parameter. Name of the webapp.  ### 
        'name': "{{ item['name'] | default('') }}" 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
         ###  Required parameter. The name of the slot.  ### 
        'slot': "{{ item['slot'] | default('') }}" 
         ###  Optional parameter. Source slot to clone configurations from. Use webapp's name to refer to the production slot.  ### 
        'configuration-source': "{{ item['configuration-source'] | default('') }}" 
 - debug: msg="{{ az_webapp_deployment_slot_create }}"          
 - name: "az webapp deployment slot create: Create a deployment slot." 
   command: |                                      
     az webapp deployment slot create                            
                 --name {{ az_webapp_deployment_slot_create.input['name'] }} 
                 --resource-group {{ az_webapp_deployment_slot_create.input['resource-group'] }} 
                 --slot {{ az_webapp_deployment_slot_create.input['slot'] }} 
                 {%if az_webapp_deployment_slot_create.input['configuration-source'] %} --configuration-source az_webapp_deployment_slot_create.input['configuration-source'] {%endif %} 
   register: output  
 - set_fact: 
    az_webapp_deployment_slot_create: "{{ az_webapp_deployment_slot_create|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_webapp_deployment_slot_create }}" 
