

 - name: Set input params for az_webapp_config_hostname_list
   set_fact: 
     az_webapp_config_hostname_list:
       input: 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
         ###  Required parameter. Webapp name. You can configure the default using 'az configure --defaults web=<name>'.  ### 
        'webapp-name': "{{ item['webapp-name'] | default('') }}" 
         ###  Optional parameter. The name of the slot. Default to the productions slot if not specified.  ### 
        'slot': "{{ item['slot'] | default('') }}" 
 - debug: msg="{{ az_webapp_config_hostname_list }}"          
 - name: "az webapp config hostname list: List all hostname bindings for a web app." 
   command: |                                      
     az webapp config hostname list                            
                 --resource-group {{ az_webapp_config_hostname_list.input['resource-group'] }} 
                 --webapp-name {{ az_webapp_config_hostname_list.input['webapp-name'] }} 
                 {%if az_webapp_config_hostname_list.input['slot'] %} --slot az_webapp_config_hostname_list.input['slot'] {%endif %} 
   register: output  
 - set_fact: 
    az_webapp_config_hostname_list: "{{ az_webapp_config_hostname_list|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_webapp_config_hostname_list }}" 
