

 - name: Set input params for az_webapp_config_ssl_bind
   set_fact: 
     az_webapp_config_ssl_bind:
       input: 
         ###  Required parameter. The ssl cert thumbprint.  ### 
        'certificate-thumbprint': "{{ item['certificate-thumbprint'] | default('') }}" 
         ###  Required parameter. Name of the web. You can configure the default using 'az configure --defaults web=<name>'.  ### 
        'name': "{{ item['name'] | default('') }}" 
         ###  Required parameter. Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.  ### 
        'resource-group': "{{ item['resource-group'] | default('') }}" 
         ###  Required parameter. The ssl cert type.  ### 
        'ssl-type': "{{ item['ssl-type'] | default('') }}" 
         ###  Optional parameter. The name of the slot. Default to the productions slot if not specified.  ### 
        'slot': "{{ item['slot'] | default('') }}" 
 - debug: msg="{{ az_webapp_config_ssl_bind }}"          
 - name: "az webapp config ssl bind: Bind an SSL certificate to a web app." 
   command: |                                      
     az webapp config ssl bind                            
                 --certificate-thumbprint {{ az_webapp_config_ssl_bind.input['certificate-thumbprint'] }} 
                 --name {{ az_webapp_config_ssl_bind.input['name'] }} 
                 --resource-group {{ az_webapp_config_ssl_bind.input['resource-group'] }} 
                 --ssl-type {{ az_webapp_config_ssl_bind.input['ssl-type'] }} 
                 {%if az_webapp_config_ssl_bind.input['slot'] %} --slot az_webapp_config_ssl_bind.input['slot'] {%endif %} 
   register: output  
 - set_fact: 
    az_webapp_config_ssl_bind: "{{ az_webapp_config_ssl_bind|combine({'output':output.stdout|from_json}) }}"  
 - debug: msg="{{ az_webapp_config_ssl_bind }}" 
